### DISCUSSION TITLE
How to exclude all module inside directory

### DISCUSSION THREAD

**Discussion by rrifafauzikomara** [invertase/melos#334] [Q&A]
For example, I have two modules namely `home` and `auth` inside the directory `features`

The path for that modules is like this:
```dart
features/home
features/auth
```

If I want to include all the modules inside `features`, I add them like this:
```
packages:
  - features/**
  - '*'
```

But how if I want to exclude all the modules inside `features`? So all the modules inside `features` will not affected by melos

**Comment by blaugold** [comment]
We recently improved how packages are found (https://github.com/invertase/melos/pull/330), so make sure you are on the latest version of Melos.

You can ignore specific paths or all paths matched by glob expression with the [`ignore`](https://melos.invertase.dev/configuration/overview#ignore) option. Matched paths are subtracted from the paths included by the `packages` option.

```yaml
packages:
  # Include the package at the workspace root.
  - .
  # Include only the package in directory a.
  - a
  # Include all the packages in direct child directories of directory b.
  - b/*
  # Include all the packages in child directories of directory c, at any level.
  - c/**
ignore:
  # Ignore the package in b/d but not any other package in b.
  - b/d
  # Ignore all packages in a directoy named example at any level in directory c.
  - c/**/example
```

This configuration includes all packages in the repo, except those in `features`:

```yaml
packages:
  - '**'
ignore:
  - features/**
```

**Reply by rrifafauzikomara** [reply]
Hi @blaugold , thanks for the answer.

I use `melos: ^2.5.0`, And I already add `ignore` (example attached). 
<img width="875" alt="Screen Shot 2022-06-27 at 11 47 32 AM" src="https://user-images.githubusercontent.com/26451363/175862292-37b91f0b-ad31-43a7-9b75-60902c8adafd.png">

But still not working when execute `melos check_fluttter_format_all`, because the module inside `bricks` still executed by melos.

This is the script for `melos check_fluttter_format_all`.
```
  check_flutter_format:
    run: melos exec --fail-fast -- "flutter format --set-exit-if-changed --dry-run ."
    description: Run flutter format for a specific package in this project to ensure the Dart and Flutter code is formatted correctly
    select-package:
      flutter: true

  check_flutter_format_all:
    run: melos run check_flutter_format --no-select
    description: Run flutter format for all package in this project to ensure the Dart and Flutter code is formatted correctly
```

Example Error:
```
line 13, column 98 of bricks/template/feature_module/__brick__/{{package_name.snakeCase()}}/lib/data/repositories/{{package_name.snakeCase()}}_repository_impl.dart: Expected to find ';'.
```

Expected: Melos cannot execute / must ignore all modules inside the `bricks` directory
