### DISCUSSION TITLE
Increase the number of "dart/melos runners" or "instances"

### DISCUSSION THREAD

**Discussion by christianruppert** [invertase/melos#374] [Q&A] [answered]
Hello,
first of all a big thank you for creating this tool - I was able to speed up our build time from 13 to 3 minutes. Awesome!

Now for my question, we have a project with roughly 10 packages (all local at the moment).
It seems like a major aspect of the increase in speed is due to "multiple runners" melos somehow uses.

We are only using a fraction of the features, mainly the following:

```
packages:
  - '*'

scripts:
    pub:
      run: melos exec -- "fvm flutter pub get"
    pack:
      run: melos exec -- "fvm flutter packages pub get"
    build:
      run: melos exec -- "fvm flutter packages pub run build_runner build --delete-conflicting-outputs"
```
Before using melos we were using scripts to execute these commands on all packages - resulting in e.g. nearly 3 minutes for the pub get / packages get due to startup and shutdown times of the script. The build command took around 10 minutes.

When running with melos it seems like the execution happens more or less concurrent - speeding up most stuff by a factor of 4.

My question - is there any flag within melos which configures how many processes to run in parallel?
I have the feeling on my machine it might be 4 instances running - is this defined by CPU count, or e.g. some general setting in Dart?

The actual build time will most likely not benefit so much from "spawning" more processes (still might give it a try) - but the pub get scripts might become even faster if its possible to increase the number of proccesses.

So maybe you can point me in the right direction (if you know what I am talking about) - maybe there is some setting in Dart or melos to increase the number of concurrent executions.

If not - even the current reduction is awesome, thanks a lot again.

Cheers,
Chris
