### DISCUSSION TITLE
Concurrency flag leads to weird behaviour

### DISCUSSION THREAD

**Discussion by christianruppert** [invertase/melos#375] [Q&A]
Hello,
I thought I start a new thread, maybe its a bug - maybe I am just using it wrong. The concurrency flag is behaving weird. I tried to use it to start multiple e.g. pub gets on the packages (we have 13) to speed up certain things.

It seems to (properly) default to 5 if you do not touch it at all (which might be actually a good value, so this question is kind of low priority). But as soon as you play around with the flag the behaviour becomes a bit crazy.

In our main project I ran into infinite loops, pub get and builds basically were not finishing or got plenty confused (conflict message, all kind of funny stuff).

So I set up a small sample project which basically has a config like:
```
name: flutter_app_a
packages:
  - 'packages/*'

scripts:
    echo:
      run: melos exec -- "echo HELLO"
    echo10:
      run: melos exec -- "echo HELLO"
      exec:
        concurrency: 10
    echo1:
      run: melos exec -- "echo HELLO"
      exec:
        concurrency: 1
```
The project structure is quite simple, app includes a, b and c, where a and b include lib_a_b and c has lib_c
But I actually don't think it matter much for this issue (I was suspecting our includes were messing things up in the main project, but the behaviour is similar in this simple project)

If I execute melos (each of the option after each other) I get the following output:

[output.txt](https://github.com/invertase/melos/files/9560371/output.txt)

This seem kind of weird. 
Lines like [package_lib_c]: [package_lib_a_b]: HELLO

I have no idea whats up here, maybe its intended behaviour, maybe some bug. I am running on windows, very simple project, if you want I can zip it and provide it. But I think I might just be misunderstanding something, or the concurrency option might be buggy in my setup.

Cheers,
Chris

PS: Really low prio, the default of 5 works fine - I just thought I mention it if anybody has similar issues.

**Comment by blaugold** [comment]
Thanks for all the details!

You're running into a subtlety of how `run` and `exec` work together, and `melos exec` is getting invoked nested in another `melos exec`.

In the simple case where you want to run a script only in the workspace root, pass it directly to `run`:

```yaml
scripts:
  hello:
    run: echo "Hello"
```

You don't need to use `melos exec -- "<command>"` to run a command in multiple packages in `melos.yaml`.

If you don't need to specify options for `melos exec`, just specify the command in `exec`:

```yaml
scripts:
  hello:
    exec: echo "Hello"
```

To specify options for `melos exec`, specify the command in `run` and the options in `exec`:

```yaml
scripts:
  hello:
    run: echo "Hello"
    exec:
      concurrency: 1
```
