### DISCUSSION TITLE
Best way to execute build_runner on all packages? (dart and flutter)

### DISCUSSION THREAD

**Discussion by ynnob** [invertase/melos#447] [Q&A] [answered]
Hey i am using melos locally as well in an azure pipeline to bootstrap and build the packages. We have Flutter and Dart packages.

**The Project looks like this:**

Base (Flutter)
--> packages/
------> package1 (dart)
------> package2 (flutter)
------> package3 (flutter)

To build the Project i run:

1. `melos bs`
2. `melos build`

melos build is a custom script that looks like this:
```
  build:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    select-package:
      depends-on: build_runner
```

The problem is that packages that are not dependend on the flutter sdk can't be build this way because they got bootstrapped as a dart project. Executing `flutter pub run build_runner` on the dart package will result in an error like mentioned in #117 but is not really related to that issue.

```
The pubspec.lock file has changed since the .dart_tool\package_config.json file was generated, please run "flutter pub get" again.
pub finished with exit code 65
```

If i want to keep this one command to execute all build requests i need to add the flutter sdk to the dart package like described in #317 

```
dependencies:
  ...
  flutter:
    sdk: flutter
```

This will allow the script to build successfully. Is there a way to avoid this workaround? Could melos decide what executebale should be used based on the package like with `melos bs`? Maybe @blaugold

**Comment by blaugold** [comment, marked as answer]
`dart run build_runner build --delete-conflicting-outputs` should work for both Flutter and Dart packages. 

I would also recommend enabling `usePubspecOverrides`, if you haven't:

```yaml
command:
  bootstrap:
    usePubspecOverrides: true
```

If you do, you will also want to add `pubspec_overrides.yaml` to your `.gitignore` file.
