### DISCUSSION TITLE
Best way to work with flavor and env vars?

### DISCUSSION THREAD

**Discussion by v41e** [invertase/melos#598] [Q&A]
Hi Melos community 👋 ,

I'm new to Melos and I'm trying to achieve something that could work with flavor

For now I have a Makefile with multiple `.env` files and several scripts and by soucing a specific file I can work with flavor with ease.

I want to achieve something similar with melos to make monorepo way  simplier.

I found a way like this:

```yaml
  build:android:
    description: Build Android app
    exec:
      concurrency: 5
      failFast: true
      orderDependents: true
    run: |
      flutter build appbundle \
        --${FLUTTER_BUILD_MODE:=release} \
        --flavor ${FLUTTER_FLAVOR:=dev} \
        --target lib/main_${FLUTTER_FLAVOR:=dev}.dart
    packageFilters:
      dirExists:
        - android
      flutter: true

  build:android:dev:
    run: melos run build:android
    env:
      FLUTTER_FLAVOR: dev
  build:android:test:
    run: melos run build:android
    env:
      FLUTTER_FLAVOR: qa
  build:android:stage:
    run: melos run build:android
    env:
      FLUTTER_FLAVOR: stage
  build:android:prod:
    run: melos run build:android
    env:
      FLUTTER_FLAVOR: prod
```

But I think that if I make repeat it for iOS web and also for publish, there are a lot of duplicates

Is there a better way to achieve this? What is recommended in this case?

Is there a way to source and env file easily?

Something like that could be awesome:

`melos run build:android --config-file=.env.dev`
