### DISCUSSION TITLE
Order builds by package

### DISCUSSION THREAD

**Discussion by jeremy-giles** [invertase/melos#767] [Q&A] [answered]
Hello, I am looking for a way to first run the build of the modules of `packages/*`, then of `features/*` and finally of `apps/*`.
Why? because as it stands the modules of `features/*` use `Freezed` entities contained in `packages/*`.

```
name: my_app
packages:
  - packages/*
  - features/*
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  pubget:
    exec: flutter clean && flutter pub get && dart pub get

  pubupgrade:
    exec: flutter pub upgrade

  build:
    run: |
      melos run build:packages && \ 
      melos run build:features && \ 
      melos run build:apps
    description: Build all packages, features and apps in this order to prevent freezed build.
    select-package:
      depends-on: build_runner

  build:packages:
    run: cd packages && dart run build_runner build --delete-conflicting-outputs
    description: Launch a fresh Build runner for packages.

  build:features:
    run: cd features && dart run build_runner build --delete-conflicting-outputs
    description: Launch a fresh Build runner for features.

  build:apps:
    run: cd apps && dart run build_runner build --delete-conflicting-outputs
    description: Launch a fresh Build runner for apps.
```

```
melos run build:packages
  └> cd packages && dart run build_runner build --delete-conflicting-outputs
     └> RUNNING

Could not find package `build_runner` or file `build_runner`
```

**Comment by spydon** [comment, marked as answer]
I would suggest to just generate all files within packages that depend on build_runner and go through with `--order-dependents`, so that it does the leaf dependencies first, like this for example:
```yaml
  generate: >
    melos exec -c 1 --order-dependents --fail-fast --depends-on="build_runner" -- \
      dart run build_runner build --delete-conflicting-outputs
```
If you're having circular dependencies that won't work though.

If you have circular dependencies I would recommend that you create three categories, and then use `exec` on each category in order: 
https://melos.invertase.dev/configuration/overview#categories
https://melos.invertase.dev/filters#--category

Currently you are trying to run `build_runner` outside of a dart/flutter project, hence why it doesn't find it.

**Reply by jeremy-giles** [reply]
Thanks for the feedback @spydon

I tried to use it this way to play the `melos build` command (like our CI will do) but without success.
```
packages:
  - packages/*
  - features/*
  - apps/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  build: >
    melos exec -c 1 --order-dependents --fail-fast --depends-on="build_runner" -- \
    dart run build_runner build --delete-conflicting-outputs
```

Zsh terminal result:
```
melos run build
  └> melos exec -c 1 --order-dependents --fail-fast --depends-on="build_runner" -- \
     dart run build_runner build --delete-conflicting-outputs
     └> RUNNING

$ melos exec
  └> dart run build_runner build --delete-conflicting-outputs
     └> RUNNING (in 28 packages)


melos run build
  └> melos exec -c 1 --order-dependents --fail-fast --depends-on="build_runner" -- \
     dart run build_runner build --delete-conflicting-outputs
     └> SUCCESS
```
But nothing was built.

**Reply by spydon** [reply]
Try to run without `--order-dependents`, just to see if it runs in any packages.
Also, which melos version are you using?

**Reply by jeremy-giles** [reply]
`melos: ^4.1.0`

Sorry I didn't understand the `generate` (which is here a script name).
By removing --order-dependents yes it builds. I ran a pipeline to see if this fixes our issue of frozen entity builds in the wrong order.
```
melos run generate
  └> melos exec -c 1 --fail-fast --depends-on="build_runner" -- \
       dart run build_runner build --delete-conflicting-outputs
     └> SUCCESS
```

On the other hand, the complete build is much longer. With a lot of logs like:
```
This may cause less efficient builds, see the following doc for help:
https://github.com/dart-lang/build/blob/master/docs/faq.md#unable-to-read-asset-could-not-compute-transitive-deps
[WARNING] build_resolvers:transitive_digests on package:items/infrastructure/item_api_interface.dart:
Unable to read asset, could not compute transitive deps: utils|lib/src/synchronisation/entity_synchro_state.freezed.dart
```

**Reply by jeremy-giles** [reply]
Update to 6.2.0, build success with `--order-dependents`
```
melos run build
  └> melos exec -c 1 --order-dependents --fail-fast --depends-on="build_runner" -- \ dart run build_runner build --delete-conflicting-outputs
       
     └> SUCCESS
```

**Reply by spydon** [reply]
So you get success without it building anything?
Do you have circular dependencies in your project?

**Reply by jeremy-giles** [reply]
_So you get success without it building anything?_
Yes, the build is done well, locally as well as on the CI (Gitlab). On the other hand, we go from 3 minutes (with the previous method) to 10 minutes with this script.

_Do you have circular dependencies in your project?_
No, I don't think we have a circular dependency.

**Reply by spydon** [reply]
If you don't want to build the packages sequentially (which is what slows it down) I'd suggest you do it with categories as I linked in the initial reply.

**Reply by jeremy-giles** [reply]
Hi @spydon,
Updated the discussion with the progress of our build refactoring. The latter is not yet optimized but allows us to resolve dependency issues between modules.
Splitting into packages of modules without dependencies (init) or whose dependencies are already built (apps/*)
```
packages:
  - packages/*
  - features/*
  - apps/*

categories:
  init:
    - packages/i18n
    - packages/shared_prefs
  packages:
    - packages/utils
    - packages/api
    - packages/database
  independentFeatures:
    - features/auth
    - features/user
    - features/location
    - features/items
  features:
    - features/user_profile
    - features/catalog
    - features/dreamteam
    - features/rooms
  apps:
    - apps/*

build:
    run: |
      melos run build:init && melos run build:packages && melos run build:independentFeatures && melos run build:features && melos run build:apps

  build:init: >
    melos exec --category="init" -c 2 --fail-fast --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs

  build:packages: >
    melos exec --category="packages" -c 4 --fail-fast --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs

  build:independentFeatures: >
    melos exec --category="independentFeatures" -c 4 --fail-fast --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs

  build:features: >
    melos exec --category="features" -c 1 --order-dependents --fail-fast --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs
  
  build:apps: >
    melos exec --category="apps" -c 2 --fail-fast --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs

```
