### DISCUSSION TITLE
Bootstrap in CI often hangs indefinitely

### DISCUSSION THREAD

**Discussion by JulienLHPro** [invertase/melos#833] [Q&A]
Hi!

We are using Melos in our project and we have quite a few packages to bootstrap (110). On local machines everything works great, but as soon as we use CI machines, the boostrap command does not complete, like 3 times out of 5.

That's really all, it just doesn't complete, it hangs forever on the last package, without any log being produced. This is why I did not open an issue, I have no exception to show...

We have fourteen self-hosted runners and we could not see any correlation or pattern in the way the script fails.

Our `melos.yaml` file is simple:

```packages:
  - applications/*
  - packages/*

ide:
  intellij:
    enabled: true
```

Our Github action workflow looks like this:
```
name: Analyze on dev PR

on:
  pull_request:
    branches: ["master", "dev"]

jobs:
  analyze:
    timeout-minutes: 15
    runs-on: [self-hosted, dart]

    steps:
      - uses: actions/checkout@v4
      - uses: dcarbone/install-jq-action@v3.0.1
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "3.27.1"

      - name: Install melos
        run: dart pub global activate melos

      - name: Fetch dev branch
        run: git fetch origin dev

      - name: Fetch HEAD branch
        run: git fetch origin $GITHUB_HEAD_REF

      - name: Bootstrap
        run: melos bootstrap runPubGetInParallel=false
```

What I've tried:

- Deactivating the IntelliJ files generation
- `runPubGetInParallel=false`
- Using the Melos Github action
- `--verbose`

Any help would be extremely welcome because our entire CI is compromised right now.

Thanks for reading this!
