### DISCUSSION TITLE
mono repo dev_dependencies package version in pubspec is not updated

### DISCUSSION THREAD

**Discussion by Tristan-gu** [invertase/melos#905] [General]
I'm using mono repo in Dart, and have something like this:

-MonoRepo
   - package1
   - package2
   - packageForDevDep

`package1` and `package2` need `packageForDevDep` as dev_dependency, so I set in the root `pubspec.yaml`

```yaml
dev_dependencies:
  melos: ^7.0.0-dev.8
  packageForDevDep:
    hosted: https://myHostedpub.eu/
    version: ^8.0.0-dev.1
```

When I use `melos version` all my packages need to update to 9.0.0, but, when it's done, I have this error on `pub get`
```
dart pub get --no-example
Resolving dependencies...
Because package1depends on both packageForDevDep ^8.0.0-dev.1 and packageForDevDep, version solving failed.
exit code 1
```

I noticed that in the root `pubspec.yaml`, the version for `packageForDevDep` is not changed after `melos version`
If I change it manually to "^9.0.0", all is good.

Is it normal ?
