### ISSUE TITLE
Question: Run a command after completion of a melos script execution?

### ISSUE THREAD

**Issue by SAGARSURI** [invertase/melos#118]
Hi @Salakar 
I want to run a script that will generate HTML for the test coverage from the `lcov` file. Currently I have the following command that runs test cases and also generates code coverage.
```
melos run test
```
Now after completion of the above script. I want to run the following command only once:
```
genhtml coverage/lcov.info -o coverage/html
```
How can I achieve this?

**Comment by SAGARSURI** [comment]
I was able to achieve it using `-dir-exists="coverage"`. This will only be available in the root directory and hence executes only one time. But if you think there is a better way of doing it. Please let me know.

**Comment by Salakar** [comment]
Could you not chain the `test` command using `&&`? e.g.

```yaml

scripts:
 test:
  description: Run tests in a specific package.
  run: melos exec --concurrency=1 -- "dart pub run test --reporter expanded && genhtml coverage/lcov.info -o coverage/html" 
  select-package:
    dir-exists:
      - "test/"
```
