### ISSUE TITLE
Proposal: platform specific run scripts

### ISSUE THREAD

**Issue by 2ZeroSix** [invertase/melos#122]
#### Problem:
It seems impossible to properly support multi-platform parsing of command in `run` section without invention of its own scripting language

For example this issue #15 is caused and cannot be easily and fully fixed because of custom `cmd` and `sh` handling

#### Proposal:
allow platform specific scripts

for example
```yaml
scripts:
  my:command:
    run:
      windows: echo hey %USERNAME%
      unix: echo hey $USER
```
or
```yaml
scripts:
  my:command:
    run:
      batch: path\to\script.bat
      shell: path/to/script.sh
```

then it would be possible to pass script in `run` section as-is to underlying interpreter without any custom parsing
