### ISSUE TITLE
Run scripts concurrently on different packages.

### ISSUE THREAD

**Issue by KlausJokisuo** [invertase/melos#128]
Currently if you have 2 packages, for example:

```
packages:
  - packages/**
  - "*"
```

Here packages are:
1. packages/**
2. "*"

and you run some script that won't exit when it's done, it will never proceed to the next package on the list.

Example melos.yaml

```
name: test_project

packages:
  - packages/**
  - "*"


scripts:
  generate:watch:
    run: melos run generate:watch:dart && melos run generate:watch:flutter
    description: Build and watch all generated files for Dart & Flutter packages in this project.

  generate:watch:dart:
    run: melos exec --fail-fast --depends-on="build_runner" --no-flutter -- "dart run build_runner watch --delete-conflicting-outputs"
    description: Build and watch generated files for Dart packages in this project.

  generate:watch:flutter:
    run: melos exec --fail-fast --depends-on="build_runner" --flutter -- "flutter pub run build_runner watch --delete-conflicting-outputs"
    description: Build all generated files for Flutter packages in this project.
 
```
