### ISSUE TITLE
Question about how to access assets that are associated with other packages

### ISSUE THREAD

**Issue by carlleeswanson** [invertase/melos#133]
I'm not sure if this is the right place to be asking this... please redirect me if appropriate.

Using melos, I have set up a mono-repo that contains 2 apps, and a couple of libraries that are used by those apps. They all reside at the same level in the directory structure:
- flight_pilot_app
- flight_passenger_app
- flight_core_models_library
- flight_common_widgets_library

Generally, the exporting of the libraries works correctly for me, and the apps are able to import/use them. 

However, my apps are internationalized, as are most of the widgets that I am trying to relocate to the common_widgets_library. I need/want to use a single set of translation files across the apps and libraries. Where do I need to put those assets, and how do I reference them, in order for them to be accessible to both of the apps and to the common_widgets_library?

So far I have tried the following, without success:
1. Set up a separate library package, with the language assets specified there. The apps build, but aren't able to find the assets, giving the following runtime error:
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Unable to load asset: lang/en.json
2. Moved the language assets up the file tree (so that 'lang' is a peer to to the apps and libraries) and specifying '../lang/en.json' in the apps' pubspec.yaml files. Again, the apps aren't able to find the assets, yielding a similar runtime error:
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Unable to load asset: ../lang/en.json
3. Investigated specifying a different DefaultAssetBundle for the apps (rather than using rootBundle), but it doesn't look like that can access outside of the current app's structure either. I'm still somewhat new to Flutter, so not clear on how that really works under the hood.

Any suggestions or guidance you can provide is much appreciated!

**Comment by carlleeswanson** [comment]
Forgot to mention... I also tried using symlinks: I moved the actual translation files to another location, and replaced the 'normal' language assets with symlinks to the files in the new location. Unfortunately, it appears that Gradle doesn't properly handle symlinks, so the app wouldn't build.

**Comment by Salakar** [comment]
See https://medium.com/flutter-community/including-assets-in-a-flutter-package-dd4a82a38ca9 

e.g. `AssetImage` supports a `package` property; https://api.flutter.dev/flutter/painting/AssetImage/package.html

Or for assets in general you can in your main app specify them in your pubspec.yaml;

```yaml
flutter:
  assets:
    - packages/flight_common_widgets_library/languages/english.json
```

**Comment by carlleeswanson** [comment]
Sorry, I'm still a little confused by your reply:

> Or for assets in general you can in your main app specify them in your pubspec.yaml pointing to your common package;
> 
> ```yaml
> flutter:
>   assets:
>     - packages/flight_common_widgets_library/languages/english.json
> ```

Implementing the above change in my app's pubspec.yaml still yields the error:
`No file or variants found for asset: packages/flight_common_widgets_library/languages/english.json.`

I order for the apps to build, wouldn't the above syntax require that my flight_common_widgets_library be a child of _**each**_ of the apps (for example, in /flight_pilot_app/packages/flight_common_widgets_library)? But that precludes it from being a "common"/independent library in the monorepo. Melos generally allows me to have all of the "packages" (i.e. both the apps and the libraries) reside as _peers_ in the top-level directory of my repo. I want to avoid (I think I _need_ to avoid) having them as children of each other. I must be misunderstanding something, but I'm not sure what!

In my OP, I mentioned that I can't get the build to recognize/access assets that are outside of the current app's structure, but still within the same repo.

Is there some other magic piece of syntax or configuration that I am missing to get the build to locate the assets?

Or is there a way to get the build to correctly handle symlinks to the assets?

**Comment by carlleeswanson** [comment]
@Salakar thanks for the prompt response. However, I am still having issues with accessing the assets. I believe I have configured everything correctly based on your reply. I also found another useful article that indicates similar configuration requirements as you stated: https://medium.com/flutter-community/including-assets-in-a-flutter-package-dd4a82a38ca9

The app builds fine, but hangs with the following error (from flutter/lib/service/asset_bundle.dart, line 255):
`E/flutter (23319): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Unable to load asset: lang/en.json
`

It looks like the rootBundle isn't being built correctly. It's empty.

Could this be due to how Melos is manipulating the packages? Any other ideas?

**Directory structure**
```
flight_project_repo
/flight_pilot_app
/flight_passenger_app
/flight_core_models_library
/flight_common_widgets_library
/flight_translations_library
//lib
///lang
////en.json
////es.json
////fr.json
```
**melos.yaml**
```
name: flight_project
packages:
  - flight_pilot_app
  - flight_passenger_app
  - flight_core_models_library
  - flight_common_widgets_library
  - flight_translations_library
```

**flight_pilot_app/pubspec.yaml**
```
version: 0.2.0+137
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flight_core_models_library:
    path: ../flight_core_models_library
  flight_common_widgets_library:
    path: ../flight_common_widgets_library
  flight_translations_library:
    path: ../flight_translations_library
flutter:
  uses-material-design: true
  assets:
    # localization files
    - packages/flight_translations_library/lang/en.json
    - packages/flight_translations_library/lang/es.json
    - packages/flight_translations_library/lang/fr.json
```

**flight_translations_library/pubspec.yaml**
```
version: 0.0.1+1
environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
```
