### ISSUE TITLE
Bootstrap hangs if dependency cannot be found

### ISSUE THREAD

**Issue by dnys1** [invertase/melos#135]
The `bootstrap` command will hang on `pub get` when one of the packages cannot be found (e.g. if the name was misspelled, like `pedantc` instead of `pedantic`). This is actually quite easy to do while having `dart.runPubGetOnPubspecChanges` set to false in VSCode.

The issue is that `pub get` will keep retrying so the command never completes with an exit code, which `_runPubGetForPackage` expects. It took me a while to figure out why this was happening because there was no output to the console. One solution could be to pipe stderr for these commands to the console, instead of waiting until the command completes, which would alert the developer that something is wrong.

**Comment by richard457** [comment]
This happen randomly on packages, even when nothing is spelled or no dependency at all
Take example for this 
```
name: flutter_datetime_picker
publish_to: "none"
description: A date time picker for flutter, you can choose date / time / date&time in English Dutch and Chinese, and you can also custom your own picker content
version: 1.5.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

```
For the first time it bootstrapped then after adding more packages this started to hang.
