### ISSUE TITLE
Combining/inheriting filters

### ISSUE THREAD

**Issue by QuirijnGB** [invertase/melos#136]
I currently have a setup similar to this:

```yaml
  ## TESTING
  test:flutter:
    run: |
      melos exec --fail-fast  --dir-exists="test" --depends-on="flutter_test" --flutter -- \
        "flutter test --no-pub --machine > tests.json"
    description: Run `flutter test` for flutter packages.

  test:dart:
    run: |
      melos exec --fail-fast --dir-exists="test"  --depends-on="test" --no-flutter -- \
        "dart test --reporter=json > tests.json"
    description: Run `dart test` for dart packages.

  test:report:
    run: |
      melos exec --fail-fast --file-exists="./tests.json" -- \
       "tojunit -i tests.json -o test-report.xml"
    description: Convert the test report.

  test:
    run: |
      melos run test:flutter && melos run test:dart && melos run test:report
    description: Run all the tests.

```

Multiple similar commands with different filters combined into one command to make my life easier.

This works great, but now I want to reduce my test/build time by just testing the affected packages using `--since`

```bash
melos run test --since=v1.2.3
```
The `since` option is essentially ignored. 
Am I missing something or is it currently not possible?
