### ISSUE TITLE
Don't override user `dependency_overrides`

### ISSUE THREAD

**Issue by priyashpatil** [invertase/melos#141]
A child package with dependency referencing git does not work. It auto links packages assuming it's local. It's fine as long as code is in sync but if want to reference older version of parent package or parent package's API changed with breaking changes it also locally breaks child package's code as it references other version.  

Directory structure of example monorepo project on git repo.
```
- packages
    - parent_package
    - child_package
- melos.yaml
```

Child package's pubspec.yaml

```yaml
name: child_package
version: 2.0.1

dependencies:
  parent_package:
    git:
      url: git@github.com:org/monorepo.git
      ref: parent_package-1.0.0
      path: packages/parent_package
```

**Comment by priyashpatil** [comment]
My current workaround using melos scripts:
```yaml
name: Melos Project

packages:
  - packages/**

scripts:
  boot:project:
    run: |
      melos bs --ignore="child_package" && melos run boot:child
    description: Bootstrap packages

  boot:child:
    run: |
      cd packages/child_package && dart pub get
    description: Pull child package dependencies
```

**Comment by priyashpatil** [comment]
Adding additional flag on bootstrap command could be the possible solution. So by default it will link local packages but passing flag something like `--with-git-dep` will honor the git dependencies. So you would run command like:
```
melos bs --with-git-dep
```

**Comment by Salakar** [comment]
What do you think of this FR @rrousselGit?

**Comment by rrousselGit** [comment]
Im not sure. What is the use-case?

**Comment by priyashpatil** [comment]
This is a rare case I think. Better programming will not have this issue. In our case, we have two different teams each working on a package. One team references the old version of the other team's package. I know this shouldn't be a problem or this type of workflow might not suit the mono-repo approach. But if I'm not wrong then Melos uses package names to link dependencies locally & it does not honor any specific version of a package.  Dart pub has support for loading packages using Git refs (tag, etc.) along with linking packages locally and I think Melos doesn't honor the git dependency version if the package is local.

**Comment by rrousselGit** [comment]
In that case, maybe you want to use dependency_overrides?

```yaml
dependency_overrides:
  parent_package:
    git:
      url: git@github.com:org/monorepo.git
      ref: parent_package-1.0.0
      path: packages/parent_package
```

**Comment by priyashpatil** [comment]
I already tried that. It doesn't work.

**Comment by rrousselGit** [comment]
Hum it probably should. Thought @Salakar?

I don't think melos should override dependency_overrides

**Comment by priyashpatil** [comment]
> Hum it probably should. Thought @Salakar?
> 
> I don't think melos should override dependency_overrides

Okay. Let me isolate the issue in a separate public repo replicating my use case. Maybe I might have missed something.

**Comment by priyashpatil** [comment]
[Link to isolaterepo](https://github.com/priyashpatil/cross-depend)

Above is a link to isolated issues example. Please let me know if I'm misconfiguring somewhere.

**Comment by Salakar** [comment]
I'd say that if Melos is overriding an existing dependency_override then it is indeed a bug, should be a quick fix though

**Comment by Salakar** [comment]
Here's the code that overrides existing dependency overrides: https://github.com/invertase/melos/blob/master/packages/melos/lib/src/commands/bootstrap.dart#L213-L222 - we could check its not in the package dep overrides before adding it

**Comment by Nikitae57** [comment]
Any updates?

**Comment by zhyky** [comment]
Could this be configurable in `command/bootstrap`

There is a scene like this:

root project
  - depends on packageA 
    - depends on packageC version1
  - depends on packageB
    - depends on packageC version2

packageA, packageB and packageC are all remote git packages

To resolve dependency conflict, the packageC is override in root's dependency_overrides

However, when we git clone packageC to local, we want melos to override packageC to local dependency, but now it does not.

**Comment by busslina** [comment]
Still present this issue:

Ignored on `pubspec.yaml` and removed/overwritten on `pubspec_overrides.yaml`:
```yaml
dependency_overrides:
  equatable:
    git:
      url: https://github.com/busslina/equatable
      ref: master
```
