### ISSUE TITLE
Allow changing the default value of melos commands in the melos.yaml

### ISSUE THREAD

**Issue by rrousselGit** [invertase/melos#148]
Thought:

```yaml
commands:
  version:
    default:
      changelog: false
      git-tag-version: false
```
