### ISSUE TITLE
Can I use Melos for application project?

### ISSUE THREAD

**Issue by weichengwu** [invertase/melos#152]
My project structure:

```
- my_app
    - pubspec.yaml
    - lib
    - packages
    - melos.yaml
```

`melos.yaml` content:

```
name: my_app
packages:
    - packages/**
```

**Comment by Salakar** [comment]
Yes;

```yaml
name: my_app
packages:
  - packages/**
  - "*"
```
