### ISSUE TITLE
Add git tags for caret version range

### ISSUE THREAD

**Issue by danilofuchs** [invertase/melos#156]
## Context
We are using Melos to organize our private Flutter components monorepo.

Dependant projects use git references to securely obtain the packages like this:

```yaml
dependencies:
  my_private_package:
    git:
      url: git@github.my_org/my_monorepo.git
      path: packages/my_package
      ref: my_package-v1.0.0
```

## Problem
This introduces 2 problems:

- This makes the dependants reliant on a single version, instead of a range (`^1.0.0`)
- Internal dependencies inside the monorepo need to change their ranges everytime a new child project is updated

## Proposal

What I suggest is on `melos version`, create a tag which follows the equivalent of a caret range:
`my_package-v1.x`

This tag would be changed every time a new version within 1.x is tagged.

For unstable releases, create `my_package-v0.1.x` to follow semver correctly.
