### ISSUE TITLE
Does not work very well with git references

### ISSUE THREAD

**Issue by danilofuchs** [invertase/melos#157]
## Context
We are using Melos to organize our private Flutter components monorepo.

Dependant projects use git references to securely obtain the packages like this:

```yaml
dependencies:
  my_private_package:
    git:
      url: git@github.my_org/my_monorepo.git
      path: packages/my_package
      ref: my_package-v1.0.0
```

## Problem

When a package depends on another internal package, we cannot set a path reference as any external project which depends on the root package will not be able to resolve the paths.

So, we decided to set git references on all internal packages, expecting melos to correctly symlink the packages for us (as they do for pub.dev packages). This would make it transparent to both developers (library and app developers).

However, when we run `melos bootstrap`, melos replaces the git references in the pubspec.lock file with path references:

![Screen Shot 2021-08-11 at 12 26 17](https://user-images.githubusercontent.com/17657014/129057863-ba71d2f0-3386-4e69-93b0-e6c32711d48c.png)

This works for the library developer, but breaks for the app developer.

## Workaround

To avoid this issue, we are considering not commiting pubspec.lock on our packages, the app developers should lock their dependencies instead.
