### ISSUE TITLE
bootstrap hangs when package does not exist

### ISSUE THREAD

**Issue by Ehesp** [invertase/melos#195]
If you add a dependency in a `pubspec.yaml` file which does not exist (both locally and on pub), the `melos bs` command will hang forever:

```
dependencies:
  fooooooo: ^0.0.1
  flutter:
    sdk: flutter
```
