### ISSUE TITLE
All Commands Execute Multiple Times

### ISSUE THREAD

**Issue by scottbisaillon** [invertase/melos#198]
OS: Windows 10
Melos: 1.0.0-dev.10

Any command that I run will execute multiple times, and in some cases not terminate (for as long as I let it go at least).

This seems to happen even with `melos -v` or `melos -h` giving the following output:
```bash
melos -v
1.0.0-dev.10
1.0.0-dev.10
``` 

I have this script for testing all packages:
```yaml
scripts:
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
```
which continuously ran until I terminated it manually.

I have deactivated/re-activated to see if that fixed any issues, as well as tried a few versions (current stable along with the dev releases).

Is there something I am missing potentially?
