### ISSUE TITLE
optimize for performance on exec and run

### ISSUE THREAD

**Issue by huang12zheng** [invertase/melos#205]
**Description**

Commands `exec` and `run` maybe optimized for performance 
`melos run tag:pubspec` is slower 3s than `melos list -l`

**Requirements**

- [ ] optimized for performance 

**Additional Context**

melos run tag take about 30s
```yaml
#melso.yaml
  tag:git:
    run: melos exec "git tag -l"
    description: show all tag
  tag:pubspec:
    run: melos list -l 
    description: show all tag
  tag:gitstatus:
    run: melos exec "git status"
    description: show all tag
  tag:
    run: melos run tag:git && melos run tag:pubspec && melos run tag:gitstatus
    description: show all tag

```
