### ISSUE TITLE
[bug] `melos run` args only work in single line scripts

### ISSUE THREAD

**Issue by jeroen-meijer** [invertase/melos#232]
Hi there! 👋🏻 

@Salakar graciously added the functionality to run `melos run` scripts with additional arguments in #231. 😄

### Description

Looking at the tests and trying it out myself, it works fine in single line scripts.

```yaml
// melos.yaml

name: test_args

packages:
  - packages/**

scripts:
  testargs:
    run: echo "$0" "$1" "$2" "$3"
```

Output:

```shell
$ melos run testargs first second third
melos run testargs
   └> echo "$0" "$1" "$2" "$3"
       └> RUNNING

/bin/sh    first second third

melos run testargs
   └> echo "$0" "$1" "$2" "$3"
       └> SUCCESS
```

### Actual behavior

However, using a multi-line string in YAML to define a script breaks this behavior.

#### Example 1

```yaml
// melos.yaml

name: test_args

packages:
  - packages/**

scripts:
  testargs:
    run: |
      echo "$0" "$1" "$2" "$3"
```

Output:

```shell
$ melos run testargs first second third
melos run testargs
   └> echo "$0" "$1" "$2" "$3"
       └> RUNNING

/bin/sh   
/bin/sh: line 1: first: command not found


melos run testargs
   └> echo "$0" "$1" "$2" "$3"
       └> FAILED
ScriptException: The script testargs failed to execute
```

#### Example 2

```yaml
// melos.yaml

name: test_args

packages:
  - packages/**

scripts:
  testargs:
    run: |
      echo "Shell: $0"
      echo "First: $1"
      echo "Second: $2"
      echo "Third: $3"
```

Output:

```shell
$ melos run testargs first second third
melos run testargs
   └> echo "Shell: $0"echo "First: $1"echo "Second: $2"echo "Third: $3"
       └> RUNNING

Shell: /bin/sh
First: 
Second: 
Third: 
/bin/sh: line 4: first: command not found


melos run testargs
   └> echo "Shell: $0"echo "First: $1"echo "Second: $2"echo "Third: $3"
       └> FAILED
ScriptException: The script testargs failed to execute
```

### Expected behavior

I believe arguments should be handled independently of the format of the script payload provided to Melos, just like when executing a `some_script.sh first second third` would parse `$1`, `$2`, etc. correctly.

---

If you need any additional info or help, feel free to reach out! 😄 
Great job y'all 👍🏻

**Comment by Salakar** [comment]
Doh, need to tinker with this one since the current implementation just passes them along as [additional args at the end of the script](https://github.com/invertase/melos/blob/main/packages/melos/lib/src/commands/run.dart#L151), maybe I need to explicitly define positional args as envs myself `$0`, `$1`, etc - but then this probably is going to be a nightmare cross-platform 🤔

**Comment by jeroen-meijer** [comment]
@Salakar Yeah, I've tried it for a little bit myself, and it's trickier than it seems 😜

In bash, functions aren't first class citizens, so you can't simply define an anonymous one and call it immediately.

However, one idea I had was, wrap any script you get in the following:
```dart
"_run_melos_script() { $scriptPayload ; }"
```

Then simply run the script and append the arguments
```dart
final scriptFunction = "_run_melos_script() { $scriptPayload ; }"
await _startProcess("$scriptFunction && _run_melos_script ${restArgs.map((arg) => '"$arg"').join()}")
```

It's a bit rough, but I think it might do the job. I'll do some experimenting. Lmkwyt 😄

**Comment by Salakar** [comment]
I'm fine with it being a bit rough if it works, but it would also need to work on Windows too 😭

**Comment by jeroen-meijer** [comment]
![image](https://user-images.githubusercontent.com/14292245/151429458-29144ca4-793e-45a9-962b-3a2defd668ae.png)

Good point. I'll have a think about it...

In the current implementation, all provided scripts are processed _as-is_ in bash on POSIX platforms and in CMD on Windows, is that right? 👀

**Comment by chenz0OO** [comment]
I wonder if this would also fix an issue I'm having trying to pass in a variable:

I'm trying to use this command in a melos script:

```shell
melos exec --since=<commit hash> -- flutter test
```

where the commit hash could be passed in dynamically like:

```shell
melos exec --since=$1 -- flutter test
```

I can't see any way to do this currently from the documentation. I've tried running (in various forms):

Melos script:

```yaml
args:
    description: args test
    run: melos exec --dir-exists=$1 flutter test
```

Melos command:

```shell
melos args test
```

which produces:

```shell
$ melos exec
  └> flutter test test
     └> RUNNING (in 5 packages)
```
