### ISSUE TITLE
request: Possibility to run scripts in predefined sequential order

### ISSUE THREAD

**Issue by spydon** [invertase/melos#244]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos run <script> --order first_package third_package second_package

### Description

Some scripts should not run concurrently since they might depend on the something done for another package having done the same action first, so it would be good to have a way to run scripts sequentially in a defined order.
Maybe something like this:

```yaml
scripts:
  a: ...
  b:
    run: ...
    depends_on:
      - a
```

<del>

scripts:
  build-something:
    run: ...
    order:
      - first_package
      - third_package
      - second_package

</del>

### Reasoning

I think that this feature would be useful since all types of scripts won't work to run concurrently.

**Comment by blaugold** [comment]
A related feature would be the ability to declare dependencies between scripts:

```yaml
scripts:
  a: ...
  b:
    run: ...
    depends_on:
      - a
```

This would imply a dependency graph that is a bit more flexible than a sequential list of scripts to run.
