### ISSUE TITLE
fix:  failure in nested `exec` on `run` is not reported as error at github actions.

### ISSUE THREAD

**Issue by wangmir** [invertase/melos#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.1.0

### Description

It's simple, when I run unittest at github action using melos, partial failure of the unittest is not reported as error at the `run` level cli command.

How can we reveal a partial failure to the upper command?

### Steps to reproduce

Action

```yaml
name: build_test_on_pr

on:
  push:
    branches: [ dev ]
    tags: [ '**' ]
  pull_request:

jobs:
  test:
    container:
      image:  {DOCKER}
 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "/root/.pub-cache/bin" >> $GITHUB_PATH

      - name: Melos setup
        run: |
          melos bootstrap

      - name: Test Catcha Flutter Code
        run: |
          melos run test
```

0. make a failing test on a certain package
1. `melos boostrap`
2. `melos run test`

```yaml
scripts:
  postbootstrap: melos run generate --no-select
  test:selective_unit_test:
    run: melos exec --dir-exists="test" --ignore="*example" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
  test:
    run: |
      melos run test:selective_unit_test --no-select
      melos run gen_coverage
    description: Run all Flutter tests in this project.
```

### Expected behavior

Failure reported for melos run test
Failure reported to github action.

### Additional context and comments

I don't know exact details about melos, but it seems a failure of multi-depth `run` is not reported well at the very first command.
