### ISSUE TITLE
Melos bootstrap finds somewhere old dart sdk and uses it on bootstrap of specific package

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [invertase/melos#278]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

1.5.2

### Description

For some reason, one of the packages that I use can not be bootstrapped. For some reason during pub get on that package melos thinks that I have an old dart SDK version. Unfortunately, this issue happens only with that package and that package doesn't have anything specific that can influence it. (I have other packages that have same sdk constraints and melos can bootstrap it)

mono repo structure
```
-monorepo
    -plugins
        -package
        -package
        ....
    -packages
        -package
        -package
        ....
        -folder
            -package
            -package
            ...
    -projects
        -package
        -package
```

pubspec.yaml of that package:
```
name: country_code
description: Provides list of ISO 3166-1 coutry codes in enum-like class, as well as parsing and user-assigned code elements
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4

```

melos.yaml
```
name: elopage_mobile

ignore:
  - plugins/**/example

packages:
  - plugins/**
  - packages/**
  - projects/**

command:
  version:
    branch: master

```

P.S. btw ignore in melos.yaml doesn't work as well probably my bad

### Steps to reproduce

I cannot give access to a private project to reproduce it unfortunately, however I hope that smd already resolved such issues.

### Expected behavior

melos should bootstrap all the packages

### Screenshots

execution when `melos bootsrap` with that specific package repo included inside of the packages
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/59435984/163997662-f07429e1-5c74-4375-940d-400d1dca6baa.png">

execution when `melos bootsrap` without that specific package repo included inside of the packages
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/59435984/163997463-44f49ef1-c778-4ec3-86f0-a1f29496bef7.png">

flutter/dart/melos version:
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/59435984/163997827-e73f8318-ae0d-425f-85b1-420245578d63.png">

### Additional context and comments

I hope this is stupid error on my side and you already know how to help me. Thanks in advance!
