### ISSUE TITLE
fix:  scripts env in windows not working 

### ISSUE THREAD

**Issue by tmirun** [invertase/melos#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.3.1

### Description

in windows power shell the follow code does not recognize env variable

```
...
 hello:
    name: hey
    description: 'Greet the world'
    run: echo $GREETING
    env:
      GREETING: 'Hey'
...
```
if we run this script
output:
```
melos run hello
   └> echo $GREETING
       └> RUNNING

$GREETING

melos run hello
   └> echo $GREETING
       └> SUCCESS

```

### Steps to reproduce

melos run hello

### Expected behavior

**$GREETING** should be **hey**

### Screenshots

![image](https://user-images.githubusercontent.com/8052536/170555873-caac9212-2d96-4fb0-b202-f4c510a81a04.png)
