### ISSUE TITLE
fix: melos unable to detect packages if they're at the same level as the root directory

### ISSUE THREAD

**Issue by GZGavinZhao** [invertase/melos#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.4.0

### Description

Melos is unable to list any packages if the individual packages lay right inside the root folder (instead of in the `packages/` directory).

This is our current directory structure for [AngularDart](https://github.com/angulardart-community/angular). The packages I want to use `melos` with are `ngast`, `ngcompiler`, `ngdart`, `ngforms`, `ngrouter`, and `ngtest`.
```
.
├── analysis_options.yaml
├── AUTHORS
├── examples
├── goldens
├── LICENSE
├── melos_angular.iml
├── melos.yaml
├── mono_repo.yaml
├── ngast
├── ngcompiler
├── ngdart
├── ngforms
├── ngrouter
├── ngtest
├── README.md
├── _tests
├── tests
└── tool
```

Using this `melos.yaml` file, `melos` is unable to find any packages. `melos bootstrap` gives ` -> 0 packages bootstrapped`, and `melos list` gives `No packages were found with the current filters.`.
```
name: angular
repository: https://github.com/angulardart-community/angular

packages:
  - ngast
  - ngcompiler
  - ngdart
  - ngforms
  - ngrouter
  - ngtest

ignore:
  - _tests
  - examples
  - goldens
  - tests

command:
  bootstrap:
    usePubspecOverrides: true
```

### Steps to reproduce

Enter an empty directory (I called it `melosdir`). Create three packages:
```bash
dart create -t package melos1
dart create -t package melos2
dart create -t package melos3
```

Current directory structure:
```
myfolder
└── melosdir -> root directory
    ├── melos1
    ├── melos2
    ├── melos3
    ├── melos_melosdir.iml
    └── melos.yaml
```

Use the following `melos.yaml` file:
```yaml
name: melosdir

packages:
  - melos1
  - melos2
  - melos3
```

Run `melos bootstrap` or `melos list`:
`melos bootstrap`:
```
melos bootstrap
  └> /XXX/melosdir

Running "dart pub get" in workspace packages...

Linking workspace packages...
  > SUCCESS

Generating IntelliJ IDE files...
  > SUCCESS

 -> 0 packages bootstrapped
```

`melos list`:
```
No packages were found with the current filters.
HINT: If this is unexpected, try running the command again with a reduced number of filters applied.
```

### Expected behavior

When running both commands, `melos` should be able to find three packages.

**Comment by blaugold** [comment]
It's a little unintuitive, but using `'*'` to select packages in the repo root should work.
```yaml
packages:
  # e.g. all packages inside the /packages directory
  - packages/**
  # e.g. including the workspace root as a package
  - "*"
```

**Comment by GZGavinZhao** [comment]
@blaugold Doesn't work.
```yaml
name: melosdir

packages:
  - "*"
```

`melos bs` and `melos list` still give me the same output.
