### ISSUE TITLE
fix: Property dependencies and dev_dependencies are not allowed in melos.yaml

### ISSUE THREAD

**Issue by DFelten** [invertase/melos#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.6.0

### Description

In the example projects, there are also dependencies or dev_dependencies items in the melos.yaml. For example within the [melos.yaml](https://github.com/fluttercommunity/plus_plugins/blob/main/melos.yaml) of the `plus_plugins`.

I had assumed that I could use them to update the versions of the dependencies in thepubspec.yaml of the packages within my mono repo. However, these settings have no effect and the VS Code Melos plugin tells me that this property does not exist.

Does this functionality no longer exist? We have a mono repository with lots of packages and therefore created a separate package just for dependencies. I was hoping that we could remove that through melos.

### Steps to reproduce

Add these lines to the melos.yaml and run `melos bootstrap`

```yaml
name: test_app
sdkPath: .fvm/flutter_sdk

packages:
  - "packages/**"

dependencies:
  bloc: ^8.0.2

dev_dependencies:
  build_runner: ^2.2.0
```

### Expected behavior

Dependencies of the packages should be set to the version we define within the `melos.yaml`.
