### ISSUE TITLE
fix:  melos bs in github actions

### ISSUE THREAD

**Issue by maxzod** [invertase/melos#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.6.0

### Description

Melos throws  `BootstrapException` on GitHub actions with this configuration
```yml
command:
  bootstrap:
    usePubspecOverrides: true
```
after digging a while  on `FlutterFire` they did not use this config and added 
```yml
command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
```
at https://github.com/firebase/flutterfire/pull/8916

after i used it it solved the problem and `melos bs ` runs locally and on GitHub action just fine 

notice i had to remove 
```yml
   usePubspecOverrides: true
```

since adding 
```yml
    runPubGetInParallel: false
```

did not fix it alone

### Steps to reproduce

  .

### Expected behavior

   .

### Screenshots

   .

### Additional context and comments

   .
