### ISSUE TITLE
Flutter format with custom file filter not working

### ISSUE THREAD

**Issue by jopmiddelkamp** [invertase/melos#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.6.0

### Description

When I want to execute a format on all project with a file filter I keep getting file not found messages.

### Steps to reproduce

```yaml
  format:
    run: |
      melos exec -- \
        "flutter format $(find . -name '*.dart' -not -name '*.freezed.dart' -not -name '*.g.dart' -not -wholename '*/generated/*')"
    description: |
      Run `flutter format .` in all packages.
```

### Expected behavior

To run the command in all projects and succeed like if I'm running the command for a single project.
```
flutter format $(find . -name '*.dart' -not -name '*.freezed.dart' -not -name '*.g.dart' -not -wholename '*/generated/*')
Formatted 344 files (0 changed) in 0.53 seconds.
```

**Comment by blaugold** [comment]
It's a quoting issue. The provided script is executed at the workspace root. At that point, parameter expansion is performed in the double-quoted string and the `find` command is executed. You need to use single quotes to pass the command line to `melos exec` without parameter expansion:

```yaml
scripts:
  format:
    run: |
      melos exec -- \
        'flutter format $(find . -name "*.dart" -not -name "*.freezed.dart" -not -name "*.g.dart" -not -wholename "*/generated/*")'
```

In general, I put all but the simplest scripts into their own bash files in `tool`. Parameter expansion gets confusing quickly when passing command through multiple shells.
