### ISSUE TITLE
running  melos publish in github action throws: CancelledException: Operation was canceled.

### ISSUE THREAD

**Issue by iapicca** [invertase/melos#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

melos: ^2.7.0

### Description

please see the error under this [job](https://github.com/iapicca/yak_packages/actions/runs/3111572913/jobs/5044010109) in the tab `publishing`

```console
melos publish
  └> /home/runner/work/yak_packages/yak_packages

Reading pub registry for package information...

The following packages WILL be published to the registry:

Package Name    Registry    Local
yak_utils       1.0.0+7     1.0.0+9
stub            1.0.0+2     1.0.0+3
yak_result      1.0.0+2     1.0.0+4
yak_runner      1.0.0+1     1.0.0+2
byte_token      1.0.0+2     1.0.0+3
yak_tween       0.1.0+10    0.1.0+11
yak_flutter     1.0.0+4     1.0.0+5
yak_test        1.0.0+0     1.0.0+1
CancelledException: Operation was canceled.



melos run publish
  └> melos run lint:format && \melos publish --no-dry-run
     └> FAILED
ScriptException: The script publish failed to execute
Error: Process completed with exit code 1.
``` 

this is the [script](https://github.com/iapicca/yak_packages/blob/master/melos.yaml)

```yaml
# ...
scripts:

  publish:
    run: |
      melos run lint:format && \
      melos publish --no-dry-run
    description: publish packageson pub.dev
    ignore:
      - examples/**
 # ...

```

### Steps to reproduce

I'm not really sure how to reproduce it aside for actually trying to publish a package on `pub.dev` from `github action`

### Expected behavior

at least having a clearer error message than `CancelledException`

### Additional context and comments

if you want to look my trial and errors you can find it [here](https://github.com/iapicca/yak_packages/issues/180)
possibly related to https://github.com/invertase/melos/issues/356

**Comment by blaugold** [comment]
You need to use the `--yes` flag to skip the prompt whether you want to proceed with publishing. Currently, we interpret no terminal as a **no** in the prompt.

**Comment by iapicca** [comment]
> You need to use the `--yes` flag to skip the prompt whether you want to proceed with publishing. Currently, we interpret no terminal as a **no** in the prompt.

I'll try immediately... this was broken :)
```yaml
      - name: 'publishing'
        run: |
          yes | melos run publish
 ```
