### ISSUE TITLE
How ignore package without select-package in yaml style

### ISSUE THREAD

**Issue by lsaudon** [invertase/melos#403]
I want to ignore packages with example in name, but i don't and select package any time.

This doesn't work:

```yaml
scripts:
  get:
    description: Get packages in a Flutter project.
    run: flutter pub get
    exec:
      concurrency: 1
      ignore: "*example"
```

When I have this, 
```yaml
scripts:
  get:
    description: Get packages in a Flutter project.
    run: flutter pub get
    exec:
      concurrency: 1
    select-package:
      ignore: "*example"
```

I need to select package
```sh
Select a package to run the get script:

1) * [Default - Press Enter]
2) app
```
