### ISSUE TITLE
request: Add groups for scripts to filter the output of the `melos run`

### ISSUE THREAD

**Issue by votruk** [invertase/melos#419]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos run --filter cicd

### Description

Providing the `groups` for scripts can help to navigate and search through `melos` scripts.

``` yaml
scripts:
  first_cicd:
    groups: [cicd]
    run: ...
  second_cicd:
    groups: [cicd]
    run: ...
  local_test:
    groups: [local]
    run: ...
  local_formatting:
    groups: [local]
    run: ...
  generate_files:
    groups: [cicd, local]
    run: ...
```

And then you can filter what type of scripts' group you want to get:
``` bash
# filtering for only 'cicd' scripts
melos run --group cicd

# will return
1) first_cicd
2) second_cicd
3) generate_files


# filtering for only 'local' scripts
melos run --group local

# will return
1) local_test
2) local_formatting
3) generate_files
```

We can go further with this feature and add a top-level item `groups` that will hold information about available groups with additional descriptions if needed:
``` yaml
groups:
  cicd:
  local:
    description: The set of scripts used for local execution
```

This can add possibility to get info about available groups and use this list as an entry point of using the `melos` tool:
```
melos groups

# will return
1) All scripts [Default - Press Enter]
2) cicid
3) local (The set of scripts used for local execution)
```

When a user clicks:
  - on 1 — will be equal to executing command `melos run`
  - on 2 — will be equal to executing command `melos run --group cicid`
  - on 3 — will be equal to executing command `melos run --group local`

### Reasoning

When the number of `melos` scripts grows it's become hard to navigate through all the scripts using `melos run` command.

The project I'm working on has about 100 scripts and the `melos run` is pretty unusable at this point. We want to continue using `melos` with plans of adding more scripts in the future. I see that developers struggle to find the script they need to. Some of them even avoid using `melos` because of that complexity. In our case, a major part of the scripts needed to be used for CI/CD only and they are not needed to be exposed for local development.

Also adding new scripts usually goes unnoticeable. Introducing `groups` can bring attention to developers when they will see eg 5 scripts instead of 4.

Having the ability to group scripts seems like a needed feature if you want to use `melos` for big projects.
