### ISSUE TITLE
Documentation: building a local app pointing to local packages repo

### ISSUE THREAD

**Issue by ffeu** [invertase/melos#43]
Hi

I couldn't find in the docs the right way to build a local app pointing to the local packages of a melos monorepo. 

Using `flutterfire` as an example, say I have an app named `app1` with this `pubspec.yaml`:

`app1/pubspec.yaml`
```yaml
...
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 0.5.3
  firebase_auth: 0.18.4+1
```

But I've cloned `flutterfire` locally and I want to test some stuff in the `app1` with the local code, so without `melos` I would do something like this:

```yaml
...
dependencies:
  flutter:
    sdk: flutter
  firebase_core: 
    path: "../flutterfire/packages/firebase_core/firebase_core"
  firebase_auth: 
    path: "../flutterfire/packages/firebase_auth/firebase_auth" 
```

But that doesn't work. I tried bootstraping (`melos bootstrap`) in one, both repos (`flutterfire` and `app1`), but couldn't make it work. 

Actually, is the manual path override necessary at all in `app1`?

I'm confident there must be a way, but I just couldn't find it in the docs and didn't manage to do it myself.

Thanks in advance

**Comment by Ehesp** [comment]
Within your `melos.yaml`, could you try adding the pages to the glob lookup? Need to check whether it supports out of directory paths though:

```
name: Melos

packages:
  - packages/**
  - "../flutterfire/packages/**"

```

**Comment by Salakar** [comment]
Melos works from packages nested from the root of the mono repo unfortunately. So you won't be able to add a packages glob going outside of the directory

However you can still create a relative symlink to a directory outside of your mono repo root which should work as melos does support symlinks (and it can also be committed and would look similar to [this](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_core/firebase_core/macos/Classes/FLTFirebaseCorePlugin.m));


```bash
git clone https://github.com/FirebaseExtended/flutterfire.git
cd mono_repo_dir
# relative symlink - which can be commited to git
ln -s ../flutterfire flutterfire
```

Update melos.yaml:

```yaml
name: Melos

packages:
  - packages/**
  - flutterfire/**
```

You may also wish to add some more explicity packages definitions for only the packages you're using - for less overhead;


```yaml
name: Melos

packages:
  - packages/**
  - flutterfire/firebase_auth/**
  - flutterfire/firebase_core/**
# etc ...
```

**Comment by Salakar** [comment]
Ok that was a lie regarding symlinks 😅 https://github.com/invertase/melos/blob/master/packages/melos/lib/src/common/workspace.dart#L141 - `followLinks` is set to false - should be ok to set it to true, I do recall now I didn't do it initially as would need to add some logic to de-duplicate packages that have identical paths and to also ignore the symlink paths Flutter generates for iOS (e.g. `ios/symlinks/plugins`)

If you're willing: a PR would be welcome, that place I linked above would be the best place to do it, you could `.toSet().toList()` after that first where to de-duplicate the paths and also inside that first where exclude any file paths containing `joinAll(['symlinks', 'plugins'])`. If you're not able to PR then I'll try get to it as soon as I can.

**Comment by ffeu** [comment]
Hi @Ehesp , I had already tried that before and just retried it, unfortunately it didn't work.

@Salakar Just tried the symlink and ran `melos` locally changing the `followLinks` to `true`. It worked! I'm taking a look to see if I can make this PR soon. I'll let you know if the task is beyond my capabilities. :)

**Comment by ffeu** [comment]
Hi @Salakar,

So, I ran `melos` with that `followLinks` changed to `true`. As it worked perfectly, I was investigating the reason for that to go on and make the changes and PR. 

The `melos.yaml` which worked in my scenario was:

```yaml
name: Melos

packages:
  - flutterfire/packages/**
```

So I learned that the duplication would only occur if I change the yaml to:

```yaml
name: Melos

packages:
  - flutterfire/packages/**
  - ios/.symlinks/plugins/**
```

So the `.symlinks` are already filtered as they're not in the melos config's packages. So I'm not sure if it's still worth adding it.

However, say we skip anything containing `joinAll(['.symlinks', 'plugins'])`. Perhaps in a scenario of `packages: **`.

There would be still the problem of regular duplication, which made me wonder: which paths should we keep? The first ones in the list? Would it matter?
