### ISSUE TITLE
request: run `melos exec` in different packages in topologically order

### ISSUE THREAD

**Issue by oravecz** [invertase/melos#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.7.0

### Description

Melos creates the proper graph, but when I execute my "generate" command, it doesn't begin generation with the graph's leaf nodes before working its way up the tree. In my case, I am building `json_serializable` and `freezed` classes and dependencies between projects are messed up because the parent is built before the child.

I've removed concurrency from my `generate` command to ensure that wasn't the issue.

Example of generate command.

```yaml
  generate:
    run: melos exec -c 1 --fail-fast -- flutter pub run build_runner build --delete-conflicting-outputs
    description: Runs any code generation controlled by the build_runner script
    select-package:
      depends-on: build_runner
```

### Steps to reproduce

I don't have a reproducible step. I'm not even sure that Melos is smart enough to call packages in the correct order, so this may be a feature request and not a bug. Seems pretty fundamental for a tool like this, though.

### Expected behavior

I expect Melos to generate a tree structure of all package dependencies, and run all leaf nodes in parallel while traversing up the tree. Melos has the proper graph data, but without this kind of logic, an option to declare build order would be acceptable.

### Additional context and comments

Currently, I workaround the problem by moving my `generate` script to `postgenerate` and manually running `generate` on the package that seems to be out of order in the `generate` script.
