### ISSUE TITLE
Feature: allow versioning private packages

### ISSUE THREAD

**Issue by ajbarry** [invertase/melos#44]
Melos appears to be just what I was looking for to help with the release process for a couple of flutter apps that have a shared (private) package. I have been looking through the docs, examples, issues etc but I am unable to figure out if our current use-case is supported. Here is a melos.yaml config that I am hoping is supported but I can't seem to use the `melos version` command to bump and generate the app changelogs as I hoped:

```
name: MyMonoRepo
packages:
  - app_common/**  # shared common package (publish_to: none)
  - admin_app/**   # flutter admin app, depends on app_common (publish_to: none)
  - user_app/**    # flutter end-user app, depends on app_common (publish_to: none)
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.24.0-0.0.pre <1.25.0"
```

The result of my command line session yields:

```console
❯ melos list --all --scope="user_app"
user_app

❯ melos version --scope="user_app"
melos version
   └> /Users/me/workspace/mymonorepo

No packages were found that required versioning.
Hint: try running "melos list" with the same filtering options to see a list of packages that were included.
```

I have tried all combinations I can think of using `--all`, `--private`, `--no-published` etc.

Is this a matter of misconfiguration, filesystem layout or something just not supported at this time?
