### ISSUE TITLE
request:  Ability to run script as standalone commands

### ISSUE THREAD

**Issue by cedvdb** [invertase/melos#442]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

I wanted to store a deployment command in the scripts of melos but as I understand it those are only intended to be run inside packages.

A common use case is a deployment command, for firebase app distribution for example we use in our ci:

```
firebase appdistribution:distribute app/build/app/outputs/flutter-apk/app-dev-release.apk --app {{ inputs.appId }} --groups "testers" --release-notes "${{ inputs.release}}"
```

It would be nice to allow melos config to have commands not tied to a package but just executed at the root. I believe this is still arguably still in the scope of melos.

### Reasoning

To centralize commands, melos seems like a good place.

**Comment by blaugold** [comment]
I believe what you want is already possible. Specifying a script with only the `run` option runs the provided command at the workspace root:

```yaml
scripts:
  foo:
    run: echo $(pwd)
```

Only if you use the `exec` option in a script will it be executed in multiple packages:

```yaml
scripts:
  foo:
    exec: echo $(pwd)

  bar:
    run: echo $(pwd)
    exec:
      concurrency: 1
```
