### ISSUE TITLE
fix:  melos exec --flutter

### ISSUE THREAD

**Issue by tcf909** [invertase/melos#451]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

The formula used to determine if a package is a flutter package or not does not consider all possibilities.

Currently it is only looking in dependencies: for something like ^\s*flutter:.* but it is valid to not include flutter in the dependencies, but rather only include flutter_test in the dev_dependencies.

I would suggest either
a) The script search for flutter: in the environment: section
b) You also include a search for flutter_test in dev_dependencies

Without this, basically no package we have that includes just flutter_test can be used with melos.

Example pubspec.yaml:
```
#...

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=3.3.9" #Added for flutter_test

dependencies:
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

### Steps to reproduce

Example pubspec.yaml:
```
#...

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=3.3.9" #Added for flutter_test

dependencies:
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
```

and run ```melos bs``` or any melos command that will try to run pub get

### Expected behavior

To not fail.
