### ISSUE TITLE
fix:  updateGitTagRefs not working for versions like 0.1.2+3

### ISSUE THREAD

**Issue by fischerscode** [invertase/melos#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

Package `test1` with the version `0.1.2+3` receives a fix. `melos version` bumps the version of test1 to `0.1.2+4`.

Package `test2` has the following dependency:
```yaml
  test1:
    git:
      url: https://github.com/octocat/melos-repo
      path: packages/test1
      ref: test1-v0.1.2+3
```

`melos version` should update the reference (when `updateGitTagRefs` is set to true). But it doesn't.

### Steps to reproduce

1. Create a new directory
2. Create two packages test1 and test2
3. Create a proper melos.yaml with `updateGitTagRefs` set to true.
4. Set the version of test1 to `0.1.2+3`.
5. Add this dependency to the package test2.
```yaml
  test1:
    git:
      url: https://github.com/octocat/melos-repo
      path: packages/test1
      ref: test1-v0.1.2+3
```
6. Run git init and commit the current state (no conventional commit message needed)
7. Change something int the test1 package and commit it as a fix.
8. Run `melos version`

### Expected behavior

`melos version` should update the reference `test1-v0.1.2+3` to `test1-v0.1.2+4`.

### Additional context and comments

I'll provide a PR.
