### ISSUE TITLE
fix: preVersionCommit script is not executed

### ISSUE THREAD

**Issue by fischerscode** [invertase/melos#460]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0 (#456)

### Description

The documentation [says](https://melos.invertase.dev/commands/version#hooks):
> `preVersionCommit`: Runs before the version commit is created. Allows you to make your own changes as part of versioning. You need to stage changes that you make yourself.

But it seems like a script called `version` has to be created.
https://github.com/invertase/melos/blob/3d857c4320d54c28fc0ad57378d57cbc4777c10b/packages/melos/lib/src/commands/version.dart#L308-L311

### Steps to reproduce

1. Create a script called `preVersionCommit` that changes files, like https://github.com/invertase/melos/blob/a1a265ececef8c128539d61c14dc04d7f1efdd1d/melos.yaml#L45
2. Run `melos version`

### Expected behavior

The script `preVersionCommit` should be executed and the changed files should be commited (you might have to `git add` them in the script).

### Additional context and comments

*I actually run the version from #456, but when reading the code, the behavior should be the same for 2.9.0.*

Maybe I'm the problem, but when renaming the script `preVersionCommit` to `version`, everything works fine.

One might argue it's a documentation mistake instead of a bug.

**Additional:**
`postversion` is not documented. https://github.com/invertase/melos/blob/3d857c4320d54c28fc0ad57378d57cbc4777c10b/packages/melos/lib/src/commands/version.dart#L328-L331

**Comment by blaugold** [comment]
@fischerscode Sorry you are running into this problem. A few days back, I refactored the command hooks a bit to make them more consistent. As part of that, the `version` hook became `preVersionCommit`. Unfortunately, the docs are a bit ahead of the last release because there currently is no mechanism to version the docs. I'm currently working towards 3.0.0 of Melos and hope to get there in the next few days.

**Comment by fischerscode** [comment]
@blaugold No worries, melos is such a great tool, and a few minor bugs should always be expected when using open source software. I just feel like it's the responsibility of the users to report bugs / unexpected behavior.

Just an idea for the 3.0 release:
<details>
<summary>As an user, I feel like it would be better if there would be a dedicated section called hooks.</summary>

```yaml
name: Example
packages:
 #....

scripts:
  # ....

hooks:
  version: echo "Do something"
  postversion: echo "Something else"
```
</details>

<details>
<summary>Or if the hooks would be a part of the commands section.</summary>

```yaml
name: Example
packages:
 #....

commands:
  version:
    preCommitHook: echo "do something"
    preVersionHook: echo "..."
    postCommitHook: echo "..."
  bootstrap:
    preHook: ...
    postHook: ...
```
</details>

*Feel free to close this issue whenever you feel like it.*
