### ISSUE TITLE
fix:  Are the docs ahead of the release code?

### ISSUE THREAD

**Issue by oravecz** [invertase/melos#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

Melos docs state that Hooks are a supported feature:

```
command:
  bootstrap:
    hooks:
      pre: echo `bootstrap command is running...`
      post: echo `bootstrap command is done`
```

They do not seem to work in the latest release version (2.9.0). 

I can still use my former method of adding a melos script named `postbootstrap`.

Perhaps this is a breaking change which will be introduced in 3.x, but the docs seem to be there already.

### Steps to reproduce

Add

```
command:
  bootstrap:
    hooks:
      pre: echo `bootstrap command is running...`
      post: echo `bootstrap command is done`
```

to your Melos project and run `melos bs`

### Expected behavior

I expect the echo statements to appear, but they don't
