### ISSUE TITLE
fix:  [Windows] Multiple command with `melos run` does not work

### ISSUE THREAD

**Issue by ferraridamiano** [invertase/melos#470]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

On Windows if you run `melos run my_script` and `my_script` contains multiple commands it will only be executed the first command. It works properly on Linux

### Steps to reproduce

Example script:

```yaml
scripts:
  my_script:
    run: |
      command1
      command2
    description: Script description
```

If you want to try on a real repo run `melos run compile_icons` on [this repo](https://github.com/ferraridamiano/ConverterNOW) (you need to `dart pub global activate vector_graphics_compiler` before)

### Expected behavior

All the commands of the script are executed on Windows
