### ISSUE TITLE
fix:  Could not find a file named "pubspec.yaml" in <melos path>

### ISSUE THREAD

**Issue by harkairt** [invertase/melos#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

2.9.0

### Description

Melos tries to find `pubspec.yaml` inside the executable when trying to run any kind of command. 

### Steps to reproduce

`melos.yaml` :
```
name: redacted

sdkPath: .fvm/flutter_sdk

packages:
  - app

scripts:
  get:
    exec: flutter pub get
```

After bootstrapping (✅) and running `melos run get` I get the following output:

```
melos run get
  └> melos exec -- "flutter pub get"
     └> RUNNING

Can't load Kernel binary: Invalid kernel binary format version.

Could not find a file named "pubspec.yaml" in "/Users/harkairt/.pub-cache/hosted/pub.dev/melos-2.9.0".


melos run get
  └> melos exec -- "flutter pub get"
     └> FAILED
ScriptException: The script get failed to execute
```

I don't understand why it tries to find a `pubspec.yaml` _inside_ melos executable.

### Expected behavior

`flutter pub get` to run properly in the app

**Comment by amukater** [comment]
@harkairt
The same issue occurs.Have you been able to resolve it?

**Comment by harkairt** [comment]
well, I decided to follow the [docs](https://melos.invertase.dev/getting-started#install-melos-in-the-workspace), which are [ahead of the my version of 2.9.0](https://github.com/invertase/melos/issues/469) 🤷‍♂️, but I created a `pubspec.yaml` in the root:
```yaml
name: <project>_workspace

environment:
  sdk: '>=2.18.0 <3.0.0'
dev_dependencies:
  melos: ^2.9.0
```
and did a `flutter pub get` in the root, now `melos.yaml` scripts are working. 

BEWARE: if you change to a branch in your project that has a different flutter version, then you might run into troubles, better to do the above stuff again. 

I don't know why, but none of the other colleagues who work on the project have the same issue 🙈
