### ISSUE TITLE
request:  Add optional error hook to all commands

### ISSUE THREAD

**Issue by charlesluzar** [invertase/melos#488]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

As a developer
I would like to run a post hook on a command error
So that I can give the user a hint of what may have went wrong

### Reasoning

In my case I wanted to use the `full_coverage` package to ensure that all of the appropriate files in our monorepo are included in test coverage reports. So, I installed the package:

`dart pub global activate full_coverage`

Then I created a script to run it in the appropriate packages in our monorepo:

```yaml
  test:coverage:generate_full:
    run: melos exec --dir-exists="lib" --fail-fast -- dart pub global run full_coverage
    description: Code generation to include all relevant files in coverage reports
```

The problem is that my team doesn't know about this new requirement of having this package installed locally. So, my options:
- I can include the installation in the script itself. Too noisy, too slow.
- I can reach out to my fellow teammates and tell them to install this package. A totally workable solution but slightly annoying, hard to audit whether it actually happened.
- I can create another script to "bootstrap" the CLI environment for devs, eg: something like `melos bootstrap_cli`
- ??

What I really wanted to do was to add a helpful message on failure, eg:
```yaml
test:coverage:generate_full:
  run: melos exec --dir-exists="lib" --fail-fast -- dart pub global run full_coverage
  description: Code generation to include all relevant files in coverage reports
  hooks:
    error: echo "[IMPORTANT] Are you sure you have full_coverage installed? eg: dart pub global activate full_coverage"
```

Another potential answer (that's probably total overkill) would be for melos to manage/interact with the globally activated packages directly, eg:
```yaml
name: Project Name
repository: https://github.com/project-name/project-name

packages:
  - products/*
  - packages/*
  - features/*

required_tools:
  - full_coverage
```

And if `full_coverage` wasn't detected in the user's PATH it'd either (a) be installed, or (b) melos would fail immediately and call out that it needs to be.
