### ISSUE TITLE
Melos 3.0 breaks select-package

### ISSUE THREAD

**Issue by RobertBrunhage** [invertase/melos#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.0

### Description
```
  generate:intl:
    run: flutter pub run intl_utils:generate
    exec:
      concurrency: 1
    description: Generate code for localization
    selectPackage:
      scope: "translation"
```

this runs on all the packages in the project even though the scope is for a single package.

### Steps to reproduce

1. Have a command run against a single package
2. please work?

### Expected behavior

It should only run the command in the package defined with selectPackage (previously select-package).

### Additional context and comments

This worked with `select-package` in `melos 2.9.0`. The command also works fine in that single package if I run it as a normal Flutter command.
