### ISSUE TITLE
fix:  Melos fail to execute on project

### ISSUE THREAD

**Issue by bounty1342** [invertase/melos#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.0

### Description

❯ melos --version
3.0.0

❯ melos list
Unhandled exception:
FileSystemException: Directory listing failed, path = '/usr/sbin/authserver' (OS Error: Permission denied, errno = 13)

### Steps to reproduce

pubspec.yaml
```
name: pika
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  melos: 3.0.0
```

melos.yaml
```
name: pika_workspace

packages:
  - /**

ide:
  intellij: false

scripts:
  get:
    exec: fvm flutter pub get
```

### Expected behavior

Melos should behave has 2.9.0 and list the projects.
