### ISSUE TITLE
request: support authentication with private pub repositories

### ISSUE THREAD

**Issue by adamzhu-xs** [invertase/melos#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.1

### Description

Below is correct url to get package versions.

https://artifactory.abc.com/artifactory/api/pub/pub-all/api/packages/my_package

Melos is using wrong url after below line of code:
https://github.com/invertase/melos/blob/5d25d9d0cde35a3234f2a7c2a5f1a3b2552b13d6/packages/melos/lib/src/package.dart#L894

https://artifactory.abc.com/api/packages/my_package  -> **this will give 404**

### Steps to reproduce

You have to setup a private pub host

### Expected behavior

Melos should works with different pub host (different urls)

**Comment by adamzhu-xs** [comment]
Need add auth header also.

    final pubToken = currentPlatform.environment['PUB_TOKEN'] ?? '';
    final response = await http.get(url, headers: {'Authorization': 'Bearer $pubToken'});

**Comment by blaugold** [comment]
In your case, the full URL for the private pub repository is **https://artifactory.abc.com/artifactory/api/pub/pub-all**. For example:

```yaml
name: myapp
dependencies:
  mypkg:
    version: ^1.0.0
    hosted:
      url: https://artifactory.abc.com/artifactory/api/pub/pub-all
      name: mypkg
```

Melos does not currently support pub repositories that require authorization, but we might be able to use the tokens managed by the `dart pub token` commands.
