### ISSUE TITLE
fix: Melos scripts `exec` only works if globally installed

### ISSUE THREAD

**Issue by Tandashi** [invertase/melos#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.1

### Description

Melos throws an error if not globally installed when running scripts that use `exec`.
This might be due to melos not running with the path it is currently executed from but rather assumes its globally installed.

**Why is this a problem?**
We currently face the issue that we can't run `melos` script that use `exec` in our CI/CD without installing it globally.

**Potential solution**:
Maybe the usage of `Platform.script` can be helpful to use the correct melos path.

```dart
# https://github.com/invertase/melos/blob/main/packages/melos/lib/src/scripts.dart#L280
final parts = [Platform.script.path, 'exec'];
```
(not tested)

### Steps to reproduce

**melos.yaml**
```yaml
name: test

packages:
  - packages/*

scripts:
  test:
    name: test
    exec: echo Hi
```

**pubspec.yaml**
```yaml
name: test_workspace

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  melos: ^3.0.1
```

Running the following will cause an error:
```bash
> flutter pub run melos run test
melos run test
  └> melos exec -- "echo Hi"
     └> RUNNING

/bin/sh: melos: command not found


melos run test
  └> melos exec -- "echo Hi"
     └> FAILED
ScriptException: The script test failed to execute.
pub finished with exit code 1
```

### Expected behavior

No failure when running the script since all other features work without the need of having melos installed globally.
