### ISSUE TITLE
fix:  The exec output log of multiple lines doesn't seem right

### ISSUE THREAD

**Issue by CaiJingLong** [invertase/melos#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.1

### Description

<img width="421" alt="image" src="https://user-images.githubusercontent.com/14145407/236478438-b6765d41-2289-42ae-9659-658f6c4f149e.png">

<img width="422" alt="image" src="https://user-images.githubusercontent.com/14145407/236478404-19854357-7929-4218-9b9b-9e9a57a2dc3d.png">

### Steps to reproduce

```yaml
scripts:
  try_build_web:
    exec: |
      flutter pub get
      flutter build web
    packageFilters:
      fileExists: lib/main.dart
```

```sh
melos try_build_web
```

### Expected behavior

The log should multiple lines.

**Comment by blaugold** [comment]
Thanks for reporting this!

Just FYI, in your example, if the first command fails, the second is still executed because the script is just passed to the system shell.

To only run the second command when the first one succeeds, in a way that works on Windows and Unixes you can use `&&` operators:

```yaml
scripts:
  try_build_web:
    exec: |
      flutter pub get && \
      flutter build web
```
