### ISSUE TITLE
request:  Teach melos to detect cycles in scripts

### ISSUE THREAD

**Issue by wujek-srujek** [invertase/melos#513]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

It is possible to create commands that call each other, e.g.:
```yaml
  foo:
    run: melos run bar
  bar:
    run: echo bar
```

However, it is also possible to create a cycle:
```yaml
  foo:
    run: melos run bar
  bar:
    run: melos run foo
```
Calling either `melos run foo` or `melos run bar` will never end.

I understand that it is a developer error, but maybe melos could detect this somehow? Judging by the output it seems that running scripts keeps track of command execution, so maybe it also keeps track of nesting, and could discover that a command to run is already in the 'stack', and print a nice explanation?

### Reasoning

It would be more difficult to introduce cycles in scripts, which would be helpful in project with many of them.
