### ISSUE TITLE
How to reference github melos plugin using flutter git syntax in pubspec.yaml

### ISSUE THREAD

**Issue by zogol** [invertase/melos#515]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

In normal projects there is a pubspec.yaml in the root directory of the plugin. 
This in turn allows the integration of flutter plugins with a direct referencing of the github url in the pubspec.yaml of the main project.
This looks like this for example.

```
  flutter_background_service:
    git:
      url: https://github.com/Wackymax/flutter_background_service.git
      ref: feature/fix-service-not-registered
```
This method works for normal plugins as described in the Flutter documentation.
But for some projects that use Melos this does not work, because there is only a melos.yaml in the root and no pubspec.yaml.

### Reasoning

I would like to be able to include Melos plugins using the same method as normal plugins.

Providing a guide that allows users to easily integrate Melos plugins without being Melos experts would be very helpful.
