### ISSUE TITLE
request: handle `./idea/runConfigurations` separately

### ISSUE THREAD

**Issue by atoka93** [invertase/melos#516]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

There is this option:
```yaml
ide:
  intellij:
    enabled: false
```
but there is no option to keep the `*.iml` files and disable the `runConfigurations` or customize the run configurations. ([also asked a question regarding this](https://github.com/invertase/melos/issues/204#issuecomment-1539797551))

Would be great to disable the run configurations for the packages and keep them for the melos commands, or other customization options.

### Reasoning

Often enough additional arguments and additional configurations are defined beside the default case.
One can live with the custom and melos generated configurations side-by-side, it would just be awesome if there was an option to customize this.

### Additional context and comments

Related issue: https://github.com/invertase/melos/issues/204
In light of that not sure if you want to implement this, but I thought I'd ask anyway

Either way: thank you, great tool!

**Comment by SoutaTanaka** [comment]
For reference, I solved this issue by creating a post hook as follows:
```yaml
command:
  bootstrap:
    hooks:
      post: |
        rm .idea/runConfigurations/melos_*
```
I hope this helps resolve your issue as well.
