### ISSUE TITLE
fix: unable to use melos after a fresh installation on macos

### ISSUE THREAD

**Issue by seb-beemenergy** [invertase/melos#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.0.1

### Description

I first installed dart and fluterr with brew then I did a fresh install of melos with
```
dart pub global activate melos
```
When I do
```
melos
```
The output is
```
Could not find a command named "CLI_LAUNCHER_LAUNCH_CONTEXT".

Usage: melos <command> [arguments]

Global options:
-h, --help        Print this usage information.
    --verbose     Enable verbose logging.
    --sdk-path    Path to the Dart/Flutter SDK that should be used. This command line option has precedence over the `sdkPath` option in the `melos.yaml` configuration file and the `MELOS_SDK_PATH` environment
                  variable. To use the system-wide SDK, provide the special value "auto".

Available commands:
  bootstrap   Initialize the workspace, link local packages together and install remaining package dependencies. Supports all package filtering options.
  clean       Clean this workspace and all packages. This deletes the temporary pub & ide files such as ".packages" & ".flutter-plugins". Supports all package filtering options.
  exec        Execute an arbitrary command in each package. Supports all package filtering options.
  list        List local packages in various output formats. Supports all package filtering options.
  publish     Publish any unpublished packages or package versions in your repository to pub.dev. Dry run is on by default.
  run         Run a script by name defined in the workspace melos.yaml config file.
  version     Automatically version and generate changelogs based on the Conventional Commits specification. Supports all package filtering options.

Run "melos help <command>" for more information about a command.
```
When I do
```
melos version
```
The output is
```
Cannot specify arguments before a command.

Usage: melos <command> [arguments]

Global options:
-h, --help        Print this usage information.
    --verbose     Enable verbose logging.
    --sdk-path    Path to the Dart/Flutter SDK that should be used. This command line option has precedence over the `sdkPath` option in the `melos.yaml` configuration file and the `MELOS_SDK_PATH` environment
                  variable. To use the system-wide SDK, provide the special value "auto".

Available commands:
  bootstrap   Initialize the workspace, link local packages together and install remaining package dependencies. Supports all package filtering options.
  clean       Clean this workspace and all packages. This deletes the temporary pub & ide files such as ".packages" & ".flutter-plugins". Supports all package filtering options.
  exec        Execute an arbitrary command in each package. Supports all package filtering options.
  list        List local packages in various output formats. Supports all package filtering options.
  publish     Publish any unpublished packages or package versions in your repository to pub.dev. Dry run is on by default.
  run         Run a script by name defined in the workspace melos.yaml config file.
  version     Automatically version and generate changelogs based on the Conventional Commits specification. Supports all package filtering options.

Run "melos help <command>" for more information about a command.
```

I think there is something wrong with my configuration but I can't find what and the output message is not clear enough to explain me what to do.

### Steps to reproduce

1. On a macos M1 machine
2. Install dart and flutter with brew
3. Install melos
4. launch melos command

### Expected behavior

Melos should work or indicate me the problem with my configuration that prevents it to work.

**Comment by seb-beemenergy** [comment]
I have the same problem on my github CI with this job configuration
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: beemenergy/action-parse-commit-message
        token: ${{ secrets.BEEMENERGY_GITHUB_READ_TOKEN }}
        path: .github/actions/action-parse-commit-message

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.x'
        cache: true
    - run: dart pub global activate melos
    - run: melos bootstrap
```
