### ISSUE TITLE
request: fileNotExists/dirNotExists package filters

### ISSUE THREAD

**Issue by ara-mentz** [invertase/melos#535]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

"fileNotExists/dirNotExists" Filter

### Description

As a developer, I want Melos to have the packageFilters "fileNotExists" and "dirNotExists" to execute scripts in packages where the specified dirs or files are missing.

### Reasoning

Sometimes it is needed to execute scripts in packages where a directory or file is not included. For example the script "pod install --repo-update" will fail if a Podfile.lock exists.

**Comment by GiancarloCante** [comment]
Hi, this would be very useful for projects that generally do not commit native files, like many examples of various packages.

```yaml
scripts:
  flutter-examples:create-android-native-files:
    run: |
      melos exec flutter create . --platforms=android --empty --project-name=$MELOS_PACKAGE_NAME
    description: >
      Create the android native files for all Flutter examples that do not have an android directory.
    packageFilters:
      flutter: true
      scope: "*example*"
      dirNotExists: "android"
```

**Comment by spydon** [comment]
I think that `--dir-exists` and `--file-exists` takes globs, so I think that you should be able to just do `dirExists: "!android"`.
If that is not the case we can re-open this.

**Comment by GiancarloCante** [comment]
@spydon 
Hi, I tried it but it doesn't work.

If you use any glob with `!` it can't find any package.

```yaml
  test-dir-not-exist:
    run: echo "Test dir does not exist"
    description: Test dir does not exist
    packageFilters:
      flutter: true
      dirExists: "!foo"
```


```
NoPackageFoundScriptException: No package found that matches with the filters defined in the melos.yaml for script test-dir-not-exist.
```

---

 Ideally I would like to use a glob like this:

```yaml
  flutter-examples:create-native-files:
    run: |
      melos exec flutter create . --empty --project-name=$MELOS_PACKAGE_NAME
    description: >
      Create the native files for all Flutter examples that don't have them.
    packageFilters:
      flutter: true
      scope: "*example*"
      dirExists: "!{android,ios,linux,macos,web,windows}"
 ```
 
But it can't find any package.

---

If you add `**` it will throw and exception:

```yaml
  test-dir-not-exist:
    run: echo "Test dir does not exist"
    description: Test dir does not exist
    packageFilters:
      flutter: true
      dirExists: "!**/foo"
```

But this case throws an exception

```
Unhandled exception:
FileSystemException: Exists failed, path = 'c:/melos_project/!**/foo' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
```
---

Or with support for a `glob` param:

```yaml
  test-c:
    run: echo "Test dir does not exist"
    description: Test dir does not exist
    packageFilters:
      flutter: true
      glob: "!**/{foo,bar}/**"
```

Thanks
