### ISSUE TITLE
fix:  ENV is not working on windows 

### ISSUE THREAD

**Issue by abdalazeez1** [invertase/melos#549]
### Is there an existing issue for this?

- [ ] I have searched the existing issues.

### Version

3.1.1

### Description

i am  trying to run this script on windows but  it's not work . i test it on ubuntu it's work fine. can anyone help me how to struct ENV in windows .

this is my script from DOCS : 
```
  hello:
   name: hey
   description: Greet the world
   run:  echo $GREETING 
   env:
     GREETING: 'Hey'`
```

### Steps to reproduce

1 create empty files 
2 copy script 
3 and run it from cmd  

### Expected behavior

echo Hey
