### ISSUE TITLE
usePubspecOverrides override via melos_overrides.yaml is not working

### ISSUE THREAD

**Issue by emersonsiega** [invertase/melos#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.1.1

### Description

I've been trying to override the "bootstrap: usePubspecOverrides" value in some internal packages only.
I thought this was possible via `melos_overrides.yaml`:

> Additionally, projects may include a melos_overrides.yaml file to override any melos.yaml field. This is useful for making untracked customizations to a project.
(https://melos.invertase.dev/configuration/overview)

My project is structured this way:
```
/apps
  /app_a
  /app_b
/packages
  /package_one
  /package_two
melos.yaml
```

### Steps to reproduce

I tried to override the `melos.yaml` settings with `melos_overrides.yaml`, by adding a melos_overrides.yaml file inside the project I want to change this default behavior:
```
/apps
  /app_a
    melos_overrides.yaml
  /app_b
/packages
  /package_one
  /package_two
melos.yaml
```

melos_overrides.yaml content:
```yaml
command:
  bootstrap:
    usePubspecOverrides: false
```

melos.yaml file, from the root:
```yaml
name: my_app
packages:
  - "apps/**"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true
```

### Expected behavior

The `melos bootstrap` command shouldn't create the `pubspec_overrides.yaml` file inside the Flutter app "apps/app_a".
