### ISSUE TITLE
fix:  packageFilters in melos.yaml should not be allowed for a 'run' script

### ISSUE THREAD

**Issue by wujek-srujek** [invertase/melos#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.1.1

### Description

`melos.yaml` allows the following configuration:
```yaml
name: foo

packages:
  - .
  - packages/*

scripts:
  analyze:
    run: dart analyze
    packageFilters:
      dirExists:
        - lib
```
This will show the prompt to choose the package to run the command for, but no matter what is chosen, it is still run in the root folder.

### Steps to reproduce

1. Configure a script with `run` (no `exec`) and package filters, and invoke it with `melos run myscript`.
2. Choose a package other than the root package.

### Expected behavior

As package filters make no sense for `run` scripts (the `run` command doesn't support them either), `melos.yaml` should be validated and report an error in this case. As of now it is very confusing as Melos behaves as if it did allow filters for `run` scripts, but then executes in the root anyway, no matter what the user chooses.
