### ISSUE TITLE
melos version works differently and in CI for private packages atleast.

### ISSUE THREAD

**Issue by sahani-deriv** [invertase/melos#603]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

3.2.0

### Description

I do not get any error but when I run `melos version --all` in github actions and in local the output is different.

Here's my melos.yaml:
```yaml
name: repo name
repository: 'repo url'

packages:
  - packages/*

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    workspaceChangelog: true
    updateGitTagRefs: true

  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
```

### Steps to reproduce

1. change any private package and make a commit
2. run melos version --all
3. run melos version -all in CI after pushing the changes
4. the output is different

### Expected behavior

`melos version --all `should work same locally and in CI
