### ISSUE TITLE
Combining scripts  

### ISSUE THREAD

**Issue by nielsenko** [invertase/melos#653]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Currently, if you want one script to execute a set of other scripts, you can do something like:
```yaml
  test:
    description: Run all tests.
    run: >-
      melos run test:unit &&
      melos run test:widget &&
      melos run test:lints &&
      melos run test:integration
```
However, since these are simply invoked in a subprocess (without a tty) the color coding you get when invoking the scripts separately is lost.

Also, only `&&` is really safe to use, so the construct is implicitly serialised, and fail-fast in nature.

I suggest some way of running a set of other scripts, allowing `melos`

- to avoid calling itself as subprocess, 
- be smarter about whether to fail or proceed, 
- and not loose the tty (color, etc.)

As above, this would also mitigate some use of multiline scripts, which come with its own set of problems.

### Reasoning

I find the `melos run x && melos run y` useful, but cumbersome, and ruining the nice output. It is definitely a nice-to-have.

**Comment by spydon** [comment]
I like the idea, any suggestion for how the API might look like?

**Comment by nielsenko** [comment]
I have a controversial one 😄 

What if `run` could only be used to invoke other scripts. To call out of melos, always use `exec`.
```yaml
  test:
    run: 
      - test:unit
      - test:widget
      - test:lints
      - test:integration
 
 test:unit:
    exec:
      command: dart test --concurrency=1 --coverage=coverage/ --file-reporter=json:test-results.json --reporter=github
      concurrency: 1 # only one project at a time to keep output sane
    packageFilters:
      dependsOn: test
      dirExists: test/
      flutter: false
```
Notice I introduced a `command:` tag under `exec`.

**Comment by spydon** [comment]
I don't think we'd want to make a breaking change of that magnitude (or ideally we'd not want to make a breaking change at all) to introduce this feature, but maybe this new "run" could just be called something else?

**Comment by nielsenko** [comment]
A few extra thoughts. 

- Script groups can contain other scripts groups, not just leaf scripts.
- Script groups should be evaluated in the order defined.
- For each member, it should be possible to define, if it is a _fail fast_ member or not. The better default is probably _fail fast_, as that will make it trivial to change `run: melos run x && melos run y` to `group: [x, y]`

**Comment by nielsenko** [comment]
You might also want to include other commands, such as `clean` and `bootstrap` in a a group 🤔

**Comment by spydon** [comment]
Looks like a good structure, would you be interested in implementing it?

**Comment by nielsenko** [comment]
@spydon Scratch my own itch so to say.. 

I assume that would require a fair bit of familiarity with the codebase that I don't currently possess. If I find time, I would like to, but it won't be this side of summer for sure.

If someone familiar with the code wants to run with it, feel free :smile:

**Comment by spydon** [comment]
Alright, maybe I'll have time to look at it at some point between the million different things I want to build. 😅

**Comment by jessicatarra** [comment]
I really like how `bitrise.yml` works as the configuration file for [bitrise.com](https://devcenter.bitrise.io/en/references/basics-of-bitrise-yml.html). It uses the `steps` key to define a series of actions in the script. The structure would be something like the following:

```yaml
scripts:
  group-name:
    description: this is the group description
    steps:
      - clean
      - bootstrap
      - other-group
      - run test
      - run analyze
```
It would be similar to a normal script, but instead of using `run` it uses `steps` and obviously these two keys are mutually exclusive. What do you think of this approach?
