### ISSUE TITLE
fix:  bootstrap dependency override failing if package is not in pub.dev

### ISSUE THREAD

**Issue by oravecz-jpmc** [invertase/melos#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

5.1.0

### Description

Melos throws an error if I attempt to override a package version specified as an override in my `melos.yaml` bootstrap config.

`pubspec.yaml`
```yaml
dependencies:
  flutter_auth_web: any
```

`melos.yaml`
```yaml
command:
  bootstrap:
    runPubGetInParallel: false

    dependencies:
      flutter_auth_web:
        git:
          url: ssh://git@bitbucketdc-cluster07-ssh.myorg.net/auth/flutter_auth_web.git
          ref: develop
```

### Error

```
% melos bootstrap
Resolving dependencies... (1.5s)
Because main depends on flutter_auth_web any which doesn't exist (could not find package flutter_auth_web at https://mypub.aws.myorg.net), version solving failed.
```

### Steps to reproduce

1. Provide a repository override in `melos.yaml` for a package that does not exist in Pub
2. run `melos bootstrap`

### Expected behavior

I would expect the version override in `melos.yaml` to take priority over any settings in the packages in my monorepo.

Hopefully, I am understanding the documentation regarding bootstrap config and what a "shared version" is.

### Additional context and comments

We run a private repository, and this package is a work in progress. I have not yet published it to our internal Pub repository.
