### ISSUE TITLE
Allow commands to be disabled

### ISSUE THREAD

**Issue by nielsenko** [invertase/melos#661]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

Recently two new commands was added to melos: `format` and `analyze` which just wrap `dart format` and `dart analyze`.

In my project `format` script is somewhat more complex than the default command:
```yaml
  format:
    description: Format code.
    # while we wait for https://github.com/dart-lang/dart_style/issues/864
    run: >-
      find lib test integration_test -name '*.dart' -not -name '*.g.dart' -not -name '*.realm.dart' -not -name 'realm_bindings.dart' 2> /dev/null
      | xargs dart format --fix
    exec: 
      concurrency: 1 # only one project at a time to keep output sane
```
It would be nice to:
1. Have the option of disabling a command, to avoid people using it mistakenly.
1. Get a warning if you have a script that conflict with a command
1. Perhaps even overwrite the behavior of a command with a script (a bit controversial as it will mess with users expectations).

### Reasoning

I got briefly bitten by this as I updated from `4.1.0` to `5.1.0`
