### ISSUE TITLE
Bootstrap changing pubspec.lock

### ISSUE THREAD

**Issue by isacjunior** [invertase/melos#68]
Currently when run `melos bs` the `pubspec.lock` files are changed. Apparently is the same as the execute `flutter pub upgrade` for all packages. This potentially causes a different version of some dependencies, I need to ensure that everyone working on the project uses the exact same versions.

**Suggestion:** 
Create a flag to don't upgrade and persist the actual `pubspec.lock` files.
```
melos bs --dont-upgrade
```

**Alternative:**

```yaml
# melos.yaml
scripts:
  install:
    run: melos exec -c 1 flutter packages get
    description: Install all dependencies.
```

Reference: https://dart.dev/guides/libraries/private-files#pubspeclock
