### ISSUE TITLE
request:  add support for message in shared dependencies

### ISSUE THREAD

**Issue by xsahil03x** [invertase/melos#692]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

There should be an option to also generate message while updating `shared dependencies`.

In projects where multiple developers are working, there can be instance where they might not know it's a generated dependency and coming from `melos.yaml`. To ensure no-one modifies the generated dependency directly in the package we should also generate a message mentioning the same.

Similar approach is being used in the Flutter repo
https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml#L33-L49

eg:
```yaml
name: package_a

environment:
	sdk: ^3.3.1 # THIS LINE IS AUTOGENERATED - TO UPDATE MODIFY "melos.yaml"
	
dependencies:
	retrofit: 4.0.3 # THIS LINE IS AUTOGENERATED - TO UPDATE MODIFY "melos.yaml"
```

The message can be configured directly in the `melos.yaml` file.
