### ISSUE TITLE
request: Filter by category

### ISSUE THREAD

**Issue by tilucasoli** [invertase/melos#726]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Description

As a developer, I want to run specific commands in specific projects based on the category that they are added to.

### Reasoning

This feature can be useful in contexts where you have specific scripts to run only in a few packages. For Instance, looking at the following structure, if I'd like to run a script in a and b, I need to use `melos exec --scope="a" --scope="b"` or other filters, but actually, I cannot run it based on a category, like packages part of lint feature.

- packages
  - a
  - b
  - c

### Additional context and comments

In my opinion, it could be added to the `melos.yml` file, such as:
```yml
# ...

categories:
  category_a:
    - packages/a
    - packages/c

# ...
```

Because of this, the filter `--category` can be created.

**Comment by tilucasoli** [comment]
@spydon What is the best in your opinion? Apply the path, like:

```yaml
# ...

categories:
  category_a:
    - packages/a
    - packages/c

# ...
```

or use the package's name?

```yaml
# ...

categories:
  category_a:
    - a
    - c

# ...
```
