### ISSUE TITLE
request:  interactive shell for `melos run macos` -> run: cd packages/my_app && flutter run -d macos

### ISSUE THREAD

**Issue by tgrushka** [invertase/melos#779]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos run myapp (already exists, but not interactive)

### Description

When I have:
```yaml
scripts:
  macos:
    run: cd packages/my_app && flutter run -d macos
```

or:
```yaml
scripts:
  macos:
    exec: flutter run -d macos
    packageFilters:
      scope: my_app
```

It does run my Flutter app. However, the shell is non-interactive, i.e. keystrokes like `R` or `Shift-R` don't work for hot reload/hot restart.

### Reasoning

I don't see any docs on this. Would be nice to be able to run app(s) from melos project root -- and an idiomatic, platform-aware way to do this actually -- maybe something better than an `exec`/`run` command hack -- that would support interactive shell and be just like `cd packages/my_app && flutter run -d my_platform`.
