### ISSUE TITLE
request:  handle flavor dependency overrides

### ISSUE THREAD

**Issue by tpucci** [invertase/melos#800]
### Is there an existing feature request for this?

- [X] I have searched the existing issues.

### Command

melos bootstrap --flavor [flavorName]

### Description

As a developer, I would like to override some dependencies thanks to the `pubspec_overrides.yaml` files.

Given some declarations in `melos.yaml` or in local `pubspec.yaml` files, running the bootstrap command would generate the right overrides.

### Reasoning

It would tackle some issues created in the flutter project (https://github.com/flutter/flutter/issues/46979).

I think `melos` could be the right place for such feature as it is the go-to tool for managing monorepos and local dependencies.

**Comment by spydon** [comment]
How do you suggest that this config would look like?

**Comment by pedrox-hs** [comment]
Maybe a possible approach for handling dependency overrides per flavor in Melos could be adding a `flavors` section in `melos.yaml`. This would allow defining specific dependency overrides for each flavor, generating the appropriate `pubspec_overrides.yaml` during `melos bootstrap`.  

For example:  

```yaml
flavors:
  lite:
    overrides:
      ads_sdk:
        path: ../libs/ads_stub
      analytics:
        name: analytics_lite
        version: ^2.0.0

  pro:
    overrides:
      ads_sdk:
        path: ../libs/real_ads
      analytics:
        name: analytics_pro
        version: ^3.0.0
```

Running `melos bootstrap --flavor lite` would apply the corresponding overrides, making it easier to manage dependencies per flavor without manually modifying `pubspec.yaml`.  

Does this approach make sense and seem feasible to implement?
