### ISSUE TITLE
fix:  Wrong format of dependency_overrides package

### ISSUE THREAD

**Issue by vietstone-ng** [invertase/melos#821]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Version

6.3.0

### Description

The format of `dependency_overrides` packages (in `pubspec_overrides.yaml`) is wrong with version `6.3.0`
```
  camera_android:
    url: https://github.com/my-name/packages.git
    ref: main
    path: packages/camera/camera_android
```
It's correct with version `6.2.0`
```
  camera_android:
    git:
      url: https://github.com/my-name/packages.git
      ref: main
      path: packages/camera/camera_android
```

### Steps to reproduce

melos: 6.3.0

### Expected behavior

6.3.0 should has the same correct format of `dependency_overrides` as 6.2.0
```
  camera_android:
    git:
      url: https://github.com/my-name/packages.git
      ref: main
      path: packages/camera/camera_android
```

**Comment by mrverdant13** [comment]
I am facing the very same issue.

**`pubspec.yaml`**
```yaml
name: altoke_common_brick_hooks
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  mason: ^0.1.0
  path: ^1.9.0
  shell:
    path: ../../../../tools/shell
  value_equality_approach:
    path: ../../../../tools/value_equality_approach

dev_dependencies:
  very_good_analysis: ^7.0.0

dependency_overrides:
  shell:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 575389c0d0d0752834361c4b4be6888ef4e32f83
      path: ./tools/shell/
  value_equality_approach:
    git:
      url: https://github.com/mrverdant13/altoke_bricks.git
      ref: 575389c0d0d0752834361c4b4be6888ef4e32f83
      path: ./tools/value_equality_approach/
```

**`pubspec_overrides.yaml` (where the `git` key is missing)**
```yaml
# melos_managed_dependency_overrides: shell,value_equality_approach
dependency_overrides:
  shell:
    url: https://github.com/mrverdant13/altoke_bricks.git
    ref: 575389c0d0d0752834361c4b4be6888ef4e32f83
    path: ./tools/shell/
  value_equality_approach:
    url: https://github.com/mrverdant13/altoke_bricks.git
    ref: 575389c0d0d0752834361c4b4be6888ef4e32f83
    path: ./tools/value_equality_approach/
```

The same result is generated when not setting any version nor path for the `shell` and `value_equality_approach` internal deps.

**More context:**
OS: macOS
Dart SDK: 3.6.0
Melos: 6.3.0
