### ISSUE TITLE
fix:  Disable intellij generation with enabled: false?

### ISSUE THREAD

**Issue by tgrushka** [invertase/melos#839]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Version

6.3.1

EDIT:
### OS

I'm on Linux, if it matters:
- Linux Mint 22 x86_64

dart --version
Dart SDK version: 3.6.0 (stable) (Thu Dec 5 07:46:24 2024 -0800) on "linux_x64"

### Description

I'm sorry if I don't understand / missed something...

I added the suggested config for disabling generation of intellij files to melos.yaml:

```yaml
name: myapp
packages:
  - packages/*

melos:
  ide:
    intellij:
      enabled: false
```

Then, I ran `melos boostrap` -- and it generated *.iml files in my root and package folders, and and an .idea folder in my root.

I removed these files, ran `melos bootstrap` again, and the intellij files still came back.

### Steps to reproduce

1. Install melos: `dart pub global activate melos`
2. Add melos.yaml and packages/myapp (Flutter app):
```yaml
name: myapp
packages:
  - packages/*

melos:
  ide:
    intellij:
      enabled: false
```
3. Run `melos boostrap`
4. Note the intellij files present.

### Expected behavior

I hope to disable these as I don't use IntellJ.

### Additional context and comments

I copied the suggested code from these docs:

https://invertase.docs.page/melos/configuration/overview#ideintellij
