### ISSUE TITLE
fix:  melos manual version with custom hosted packages

### ISSUE THREAD

**Issue by chedwin41** [invertase/melos#851]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Version

7.0.0-dev.4

### Description

I am using Melos with the new Dart workspace feature. My workspace contains multiple packages with dependencies between each other. I am trying to use Melos to manually version all the packages in this workspace. However, for each package that depends on other packages within the workspace, I get the following warning when running the command:

`WARNING: Failed to update dependency pnv_colors version to ^10.0.0 for package pnv_forms, you should probably report this issue with a copy of your pubspec.yaml file.`

Below are the pubspec.yaml files for both packages (after running the command):

```yaml
name: pnv_forms
description: Librairie de composants graphiques
version: 10.0.0
homepage: https://my-custom-git/pnv_forms.group
repository: https://my-custom-git/pnv_forms.group.git

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  animations: ^2.0.11 #Flutter team
  camera: ^0.11.0
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.1.5
  flutter_markdown: ^0.7.5 
  flutter_staggered_animations: ^1.1.1 
  flutter_staggered_grid_view: ^0.7.0 
  flutter_sticky_header: ^0.7.0 
  image_picker: ^1.1.2 
  image_size_getter: ^2.3.0
  inspector: ^2.1.0
  photo_view: ^0.15.0


  pnv_colors:
    hosted:
      name: pnv_colors
      url: https://my-custom-host.com/
    version: ^8.0.0

  pnv_dev_standardization:
    hosted:
      name: pnv_dev_standardization
      url: https://my-custom-host.com/
    version: ^8.0.0

  pnv_file_manager:
    hosted:
      name: pnv_file_manager
      url: https://my-custom-host.com/
    version: ^8.0.0

  pnv_forms_design_system:
    hosted:
      name: pnv_forms_design_system
      url: https://my-custom-host.com/
    version: ^8.0.0

  pnv_icons:
    hosted:
      name: pnv_icons
      url: https://my-custom-host.com/
    version: ^8.0.0

  pnv_log:
    hosted:
      name: pnv_log
      url: https://my-custom-host.com/
    version: ^8.0.0

  pnv_theme:
    hosted:
      name: pnv_theme
      url: https://my-custom-host.com/
    version: ^8.0.0

  pnv_traduction_resources:
    hosted:
      name: pnv_traduction_resources
      url: https://my-custom-host.com/
    version: ^8.0.0

  sliver_tools: ^0.2.12
  value_layout_builder: ^0.4.0
  webview_flutter: ^4.10.0


dev_dependencies:
  flutter_test: 
    sdk: flutter

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist

publish_to: https://my-custom-host.com/ #  https://dart.dev/tools/pub/pubspec#publish_to
```

```yaml
name: pnv_colors
description: Gestionnaire d'icones
version: 10.0.0
homepage: https://my-custom-git/pnv_resources.group
repository: https://my-custom-git/pnv_resources.group.git

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  pnv_dev_standardization:
    hosted:
      name: pnv_dev_standardization
      url: https://my-custom-host.com/
    version: ^8.0.0

dev_dependencies:
  dart_style: ^3.0.0

publish_to: https://my-custom-host.com/
```

### Steps to reproduce

Creating a reproducible example is challenging because my setup relies on custom-hosted dependencies. However, here is how you can reproduce the issue:

- Create a new Dart workspace with two packages, A and B.
- Deploy A and B to a custom-hosted service (e.g., Unpub).
- Make B depend on A.
- Run the following command:
```bash
melos version --yes --manual-version=B:10.0.0 --manual-version=A:10.0.0
```

### Expected behavior

When running the versioning command, Melos should update B's pubspec.yaml to depend on the newly created version of A.

Instead of updating B's dependency on A to the newly created version, I get the warning mentioned above.

### Screenshots

![Image](https://github.com/user-attachments/assets/75910c9d-87e1-4d1b-8aaa-f3531bce44df)

### Additional context and comments

Let me know if you need additional details or if there are specific configurations you'd like me to share!

### Other

- [ ] I'm interested in working on a PR for this.
