### ISSUE TITLE
request:  support defining packageFilters for commands in yaml file

### ISSUE THREAD

**Issue by josh-burton** [invertase/melos#865]
### Is there an existing feature request for this?

- [x] I have searched the existing issues.

### Command

format

### Description

I'd like to be able to specify package filters for a command in the yaml file, so I don't need to pass these filters each time I run the command.

```
command:
  format:
    lineLength: 120
    packageFilters:
      ignore:
        - "packages/api"
        - "."
 ```

### Reasoning

So I don't need to pass these filters each time I run the command.

### Other

- [x] I'm interested in working on a PR for this.
