### ISSUE TITLE
request:  Provides melos command bootstrap to check whether dependencies need to be updated

### ISSUE THREAD

**Issue by maxfrees** [invertase/melos#892]
### Is there an existing feature request for this?

- [x] I have searched the existing issues.

### Description

![Image](https://github.com/user-attachments/assets/0fd05f89-22f6-4df0-85c5-33c83cd1eb57)
现在我声明了 bootstrap ，但我不知道依赖是否需要更新，是否可以提供一个插件或者命令支持检测依赖项是否需要更新

### Reasoning

Provides melos command bootstrap to check whether dependencies need to be updated

### Other

- [ ] I'm interested in working on a PR for this.

**Comment by spydon** [comment]
If you're using android studio you can use this plugin: https://plugins.jetbrains.com/plugin/12400-flutter-pub-version-checker

I guess there is something similar for VSCode.

**Comment by maxfrees** [comment]
```
melos:
  ide:
    intellij:
      enabled: false

  command:
    bootstrap:
      environment:
        sdk: ">=3.6.1 <4.0.0"
        flutter: " >=3.27.3"
      dependencies:
        camera: ^0.11.1
        flex_color_scheme: ^8.2.0
        easy_localization: ^3.0.7+1
      dev_dependencies:
        flutter_lints: ^5.0.0
```

What I expect is to check the version in melos command bootstrap
