### ISSUE TITLE
request:  add command for listing melos scripts

### ISSUE THREAD

**Issue by omuomugin** [invertase/melos#895]
### Is there an existing feature request for this?

- [x] I have searched the existing issues.

### Command

melos list --scripts and melos list --scripts-key-only

### Description

I imagine that melos scripts tend to grow rather easily.
It would be useful to have a command like `gradle tasks` that outputs all defined scripts.

e.g. 
```sh 
melos list --scripts 

---------------------------------------------------------------------- 
test 

text from description 

env 
* SOME_ ENV 
* ANOTHER_ENV 
---------------------------------------------------------------------- 
another command 

description from another command

...
```

In addition to that, I would like to have the ability to enumerate only the keys of scripts.

```sh 
melos list --scripts--key-only 

test 
another command 
...
```

### Reasoning

This would save us from having to do the following on our own.

```yaml 
melos: 
  scripts: 
    tasks: 
      run: yq '.melos.scripts | keys | . []' pubspec.yaml 
    tasks:run: 
      run: melos run $(yq '.melos.scripts | keys | . []' pubspec.yaml | fzf) 
```

see also 

* https://github.com/mikefarah/yq 
 * https://github.com/junegunn/fzf

### Other

- [x] I'm interested in working on a PR for this.
