### ISSUE TITLE
fix:  dart workspace includes assets from other apps

### ISSUE THREAD

**Issue by matt3o** [invertase/melos#917]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Version

7.0.0-dev.8

### Description

Hey guys!

I have been using the new dart workspaces features and ran into an issue that's really bugging me - and I'm not even sure if this is related to melos or just a workspace thing. I split up my app into apps/ and packages/.
Now when I build app1 it will include all the assets from app2 which is super annoying since it uses big font files (at least right now). Any ideas how to resolve this?

```yaml
workspace:
  - apps/app1/
  - apps/app2/
  - packages/package1/
  - packages/package2/


    build:web:test:
      description: Build web app with development environment.
      run: melos exec -- "flutter build web --dart-define=APP_ENV=test  -o build/web/test/ --release --csp --pwa-strategy=none"
      packageFilters:
        scope: "app1"
```

Ps: Good work, although melos still has some rough edges / the docs are outdated, I am overall very happy with the tool!

### Steps to reproduce

Setup an environment with 2 apps with dart workspaces. Create an asset in app2 (location app2/assets/), then build app1. app1 build will contain app2 assets.

### Expected behavior

app1 build should not contain app2 assets

### Other

- [ ] I'm interested in working on a PR for this.
